version: "3.8"

services:
  hgs_app:
    build: app
    container_name: hgs_app
    hostname: hgs_app
    volumes:
      - /var/hgs:/var/hgs
    restart: always
    depends_on:
      - hgs_db
      - hgs_memcached
      - hgs_redis
    ports:
      - "9000:9000"
    networks:
      - hgs_net

  hgs_memcached:
    image: memcached:1.6.9
    container_name: hgs_memcached
    restart: always
    networks:
      - hgs_net

  hgs_redis:
    image: redis:6.2.3
    container_name: hgs_redis
    restart: always
    networks:
      - hgs_net

  hgs_mongo:
    image: mongo:4.4.6-bionic
    container_name: hgs_mongodb
    restart: always
    environment:
 #     MONGO_INITDB_ROOT_USERNAME: hgs
 #     MONGO_INITDB_ROOT_PASSWORD: hgshgs
      MONGO_INITDB_DATABASE: hgs
      TZ: Asia/Tokyo
    networks:
      - hgs_net
    ports:
      - "27017:27017"
    volumes:
      - hgs_mongo_vol:/data/db
      - hgs_mongo_config_vol:/data/configdb
      - /var/hgs/docker/dev/mongo_backup:/tmp/backup

  hgs_mongo_express:
    image: mongo-express
    container_name: hgs_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: hgs_mongodb
#      ME_CONFIG_MONGODB_ADMINUSERNAME: hgs
#      ME_CONFIG_MONGODB_ADMINPASSWORD: hgshgs
    networks:
      - hgs_net

volumes:
  hgs_mongo_vol:
  hgs_mongo_config_vol:
  hgs_redis_vol:

networks:
  hgs_net:

