<?php
return array(
    array('id' => '1','name' => '株式会社カプコン','acronym' => 'カプコン','phonetic' => 'かぷこん','url' => 'http://www.capcom.co.jp/','wikipedia' => ''),
    array('id' => '2','name' => 'テクモ','acronym' => 'テクモ','phonetic' => 'てくも','url' => 'http://www.tecmo.co.jp/','wikipedia' => ''),
    array('id' => '3','name' => '任天堂','acronym' => '任天堂','phonetic' => 'にんてんどう','url' => 'http://www.nintendo.co.jp/','wikipedia' => ''),
    array('id' => '4','name' => 'SCE','acronym' => 'SCE','phonetic' => 'えすしーいー','url' => 'http://www.jp.playstation.com/','wikipedia' => ''),
    array('id' => '8','name' => 'フロム・ソフトウェア','acronym' => 'フロム・ソフトウェア','phonetic' => 'ふろむそふとうぇあ','url' => 'http://www.nouten.com/top.php','wikipedia' => ''),
    array('id' => '9','name' => 'EA','acronym' => 'EA','phonetic' => 'いーえー','url' => 'http://www.eajapan.co.jp/','wikipedia' => ''),
    array('id' => '10','name' => 'マーベラスエンターテイメント','acronym' => 'マーベラスエンターテイメント','phonetic' => 'まーべらすえんたーていんめんと','url' => 'http://www.mmv.co.jp/game/','wikipedia' => ''),
    array('id' => '11','name' => 'マイクロソフト','acronym' => 'マイクロソフト','phonetic' => 'まいくろそふと','url' => 'http://www.xbox.com/ja-jp/','wikipedia' => ''),
    array('id' => '12','name' => 'セガ','acronym' => 'セガ','phonetic' => 'せが','url' => 'http://sega.jp/','wikipedia' => ''),
    array('id' => '13','name' => '日本一ソフトウェア','acronym' => '日本一ソフトウェア','phonetic' => 'にっぽんいちそふとうぇあ','url' => 'http://nippon1.co.jp/','wikipedia' => ''),
    array('id' => '14','name' => 'バンダイナムコエンターテインメント','acronym' => 'バンナム','phonetic' => 'ばんだいなむこえんたーていんめんと','url' => 'http://www.bandainamcogames.co.jp/','wikipedia' => ''),
    array('id' => '17','name' => 'スクウェア・エニックス','acronym' => 'スクエニ','phonetic' => 'すくうぇあえにっくす','url' => 'http://www.square-enix.com/jp/','wikipedia' => ''),
    array('id' => '18','name' => 'タカラ','acronym' => 'タカラ','phonetic' => 'たから','url' => 'http://www.takaratomy.co.jp/','wikipedia' => ''),
    array('id' => '19','name' => 'バンダイ','acronym' => 'バンダイ','phonetic' => 'ばんだい','url' => 'http://www.bandai.co.jp/','wikipedia' => ''),
    array('id' => '20','name' => 'GAE','acronym' => 'GAE','phonetic' => 'じーえーいー','url' => 'http://www.gae.co.jp/','wikipedia' => ''),
    array('id' => '21','name' => 'スパイク','acronym' => 'スパイク','phonetic' => 'すぱいく','url' => 'http://www.spike.co.jp/','wikipedia' => ''),
    array('id' => '22','name' => 'コンパイルハート','acronym' => 'コンパイルハート','phonetic' => 'こんぱいるはーと','url' => 'http://www.compileheart.com/','wikipedia' => ''),
    array('id' => '23','name' => 'AQインタラクティブ','acronym' => 'AQインタラクティブ','phonetic' => 'えーきゅーいんたらくてぃぶ','url' => 'http://www.aqi.co.jp/','wikipedia' => ''),
    array('id' => '24','name' => 'エスコット','acronym' => 'エスコット','phonetic' => '','url' => 'えすこっと','wikipedia' => ''),
    array('id' => '25','name' => 'ハドソン','acronym' => 'ハドソン','phonetic' => 'はどそん','url' => 'http://www.hudson.co.jp/','wikipedia' => ''),
    array('id' => '26','name' => 'Nibris','acronym' => 'Nibris','phonetic' => 'にぶりす','url' => 'http://www.nibris.net/','wikipedia' => ''),
    array('id' => '27','name' => 'D3パブリッシャー','acronym' => 'D3パブリッシャー','phonetic' => '','url' => 'http://www.d3p.co.jp/','wikipedia' => ''),
    array('id' => '28','name' => 'エニックス','acronym' => 'エニックス','phonetic' => '','url' => 'http://www.square-enix.com/jp/','wikipedia' => ''),
    array('id' => '29','name' => 'トンキンハウス','acronym' => 'トンキンハウス','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '30','name' => 'サミー','acronym' => 'サミー','phonetic' => '','url' => 'http://www.sammy.co.jp/japanese/index.jsp','wikipedia' => ''),
    array('id' => '31','name' => 'アトラス','acronym' => 'アトラス','phonetic' => '','url' => 'http://www.atlus.co.jp/','wikipedia' => ''),
    array('id' => '32','name' => 'バンプレスト','acronym' => 'バンプレスト','phonetic' => '','url' => 'http://www.banpresto.co.jp/','wikipedia' => ''),
    array('id' => '33','name' => 'インターチャネル・ホロン','acronym' => 'インターチャネル・ホロン','phonetic' => '','url' => 'http://www.interchannel.co.jp/','wikipedia' => ''),
    array('id' => '34','name' => 'ナウプロダクション','acronym' => 'ナウプロダクション','phonetic' => '','url' => 'http://www.nowpro.co.jp/','wikipedia' => ''),
    array('id' => '35','name' => 'メトロ','acronym' => 'メトロ','phonetic' => '','url' => 'http://www.metro-japan.com/','wikipedia' => ''),
    array('id' => '36','name' => 'アタリ','acronym' => 'アタリ','phonetic' => '','url' => 'http://www.atarijapan.com/','wikipedia' => ''),
    array('id' => '37','name' => 'エクシング','acronym' => 'エクシング','phonetic' => '','url' => 'http://www.xing.co.jp/','wikipedia' => ''),
    array('id' => '38','name' => 'ポニーキャニオン','acronym' => 'ポニーキャニオン','phonetic' => '','url' => 'http://www.ponycanyon.co.jp/','wikipedia' => ''),
    array('id' => '39','name' => 'ディンプル','acronym' => 'ディンプル','phonetic' => '','url' => 'http://www.dmpl.co.jp/','wikipedia' => ''),
    array('id' => '40','name' => 'アウトブレイク','acronym' => 'アウトブレイク','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '41','name' => 'ヒューマン','acronym' => 'ヒューマン','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '42','name' => 'ビー・ファクトリー','acronym' => 'ビー・ファクトリー','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '43','name' => 'ギャガ・コミュニケーションズ','acronym' => 'ギャガ・コミュニケーションズ','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '44','name' => 'アクレイムジャパン','acronym' => 'アクレイムジャパン','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '45','name' => 'ワープ','acronym' => 'ワープ','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '46','name' => 'コナミ','acronym' => 'コナミ','phonetic' => '','url' => 'http://www.konami.jp/','wikipedia' => ''),
    array('id' => '47','name' => 'ユタカ','acronym' => 'ユタカ','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '48','name' => 'アイディアファクトリー','acronym' => 'アイディアファクトリー','phonetic' => '','url' => 'http://www.ideaf.co.jp/','wikipedia' => ''),
    array('id' => '49','name' => 'サクセス','acronym' => 'サクセス','phonetic' => '','url' => 'http://www.success-corp.co.jp/','wikipedia' => ''),
    array('id' => '50','name' => 'クレイジーゲーム','acronym' => 'クレイジーゲーム','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '51','name' => 'ジャレコ','acronym' => 'ジャレコ','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '52','name' => 'メディアエンターテイメント','acronym' => 'メディアエンターテイメント','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '53','name' => 'サイバーフロント','acronym' => 'サイバーフロント','phonetic' => '','url' => 'http://www.cyberfront.co.jp/','wikipedia' => ''),
    array('id' => '54','name' => 'ビクターインタラクティブソフトウエア','acronym' => 'ビクターインタラクティブソフトウエア','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '55','name' => 'The 3DO Company','acronym' => 'The 3DO Company','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '56','name' => 'ヴィジット','acronym' => 'ヴィジット','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '57','name' => 'アイドス','acronym' => 'アイドス','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '58','name' => '角川書店','acronym' => '角川書店','phonetic' => '','url' => 'http://www.kadokawa.co.jp/','wikipedia' => ''),
    array('id' => '59','name' => 'ピーアンドエー','acronym' => 'ピーアンドエー','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '60','name' => 'アクティビジョン','acronym' => 'アクティビジョン','phonetic' => '','url' => 'http://www.activision.com/','wikipedia' => ''),
    array('id' => '61','name' => 'ライブドア','acronym' => 'ライブドア','phonetic' => '','url' => 'http://www.livedoor.com/','wikipedia' => ''),
    array('id' => '62','name' => 'Sega of America','acronym' => 'Sega of America','phonetic' => '','url' => 'http://www.sega.com/','wikipedia' => ''),
    array('id' => '63','name' => 'ソフトマックス','acronym' => 'ソフトマックス','phonetic' => '','url' => 'http://www.softmax.co.jp/','wikipedia' => ''),
    array('id' => '64','name' => 'インターチャネル','acronym' => 'インターチャネル','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '65','name' => 'パンドラボックス','acronym' => 'パンドラボックス','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '66','name' => 'ジェネックス','acronym' => 'ジェネックス','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '67','name' => 'アテナ','acronym' => 'アテナ','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '68','name' => 'ソフトバンクBB','acronym' => 'ソフトバンクBB','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '69','name' => 'ズー','acronym' => 'ズー','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '70','name' => 'Liar-Soft','acronym' => 'Liar-Soft','phonetic' => '','url' => 'http://www.liar.co.jp/index.html','wikipedia' => ''),
    array('id' => '71','name' => 'F&C・FC03','acronym' => 'F&C・FC03','phonetic' => '','url' => 'http://www.dreamsoft.jp/','wikipedia' => ''),
    array('id' => '72','name' => 'タイガーマンプロジェクト','acronym' => 'タイガーマンプロジェクト','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '73','name' => 'アボガドパワーズ','acronym' => 'アボガドパワーズ','phonetic' => '','url' => 'http://www.abopa.net/','wikipedia' => ''),
    array('id' => '74','name' => 'ネル','acronym' => 'ネル','phonetic' => '','url' => 'http://marigold.1000.tv/nel/','wikipedia' => ''),
    array('id' => '75','name' => 'Lass','acronym' => 'Lass','phonetic' => '','url' => 'http://lass.jp/','wikipedia' => ''),
    array('id' => '76','name' => 'ブルーゲイル','acronym' => 'ブルーゲイル','phonetic' => '','url' => 'http://www.bluegale.com/','wikipedia' => ''),
    array('id' => '77','name' => 'シーズウェア','acronym' => 'シーズウェア','phonetic' => '','url' => 'http://csware.himeya.com/','wikipedia' => ''),
    array('id' => '78','name' => 'MBS Truth','acronym' => 'MBS Truth','phonetic' => '','url' => 'http://www.teck.co.jp/truth/','wikipedia' => ''),
    array('id' => '79','name' => 'BLACK CYC','acronym' => 'BLACK CYC','phonetic' => '','url' => 'http://www.cyc-soft.com/','wikipedia' => ''),
    array('id' => '80','name' => '美遊','acronym' => '美遊','phonetic' => '','url' => 'http://www.mu-game.co.jp/','wikipedia' => ''),
    array('id' => '81','name' => 'ruf','acronym' => 'ruf','phonetic' => '','url' => 'http://www.ruf-soft.net/','wikipedia' => ''),
    array('id' => '82','name' => 'Project-μ','acronym' => 'Project-μ','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '83','name' => 'mirage','acronym' => 'mirage','phonetic' => '','url' => 'http://www.mirage-soft.com/','wikipedia' => ''),
    array('id' => '84','name' => 'Innocent Grey','acronym' => 'Innocent Grey','phonetic' => '','url' => 'http://www.gungnir.co.jp/innocentgrey/','wikipedia' => ''),
    array('id' => '85','name' => 'Candle','acronym' => 'Candle','phonetic' => '','url' => 'http://www.r18game.com/candle/','wikipedia' => ''),
    array('id' => '86','name' => 'TOPCAT','acronym' => 'TOPCAT','phonetic' => '','url' => 'http://www.topcat.jp/','wikipedia' => ''),
    array('id' => '87','name' => 'ジュエリー','acronym' => 'ジュエリー','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '88','name' => 'ニトロプラス','acronym' => 'ニトロプラス','phonetic' => '','url' => 'http://www.nitroplus.co.jp/','wikipedia' => ''),
    array('id' => '89','name' => 'Leaf','acronym' => 'Leaf','phonetic' => 'りーふ','url' => 'http://leaf.aquaplus.co.jp/','wikipedia' => ''),
    array('id' => '90','name' => 'D.O.','acronym' => 'D.O.','phonetic' => 'でぃーおー','url' => 'http://www.do-game.co.jp/','wikipedia' => ''),
    array('id' => '91','name' => 'シルキーズ','acronym' => 'シルキーズ','phonetic' => 'しるきーず','url' => 'http://www.silkys.jp/','wikipedia' => ''),
    array('id' => '92','name' => 'ケロQ','acronym' => 'ケロQ','phonetic' => 'けろきゅー','url' => 'http://www.keroq.co.jp/','wikipedia' => ''),
    array('id' => '93','name' => 'Gage','acronym' => 'Gage','phonetic' => 'げーじ','url' => 'http://www.gage-soft.com/','wikipedia' => ''),
    array('id' => '94','name' => 'アトリエかぐや','acronym' => 'アトリエかぐや','phonetic' => 'あとりあかぐや','url' => 'http://www.a-kaguya.com/','wikipedia' => ''),
    array('id' => '96','name' => 'アルケミスト','acronym' => 'アルケミスト','phonetic' => '','url' => 'http://www.alchemist-net.co.jp/','wikipedia' => ''),
    array('id' => '99','name' => '07th Expansion','acronym' => '07th Expansion','phonetic' => '07えくすぱんしょん','url' => 'http://07th-expansion.net/','wikipedia' => ''),
    array('id' => '100','name' => '七転び八転がり','acronym' => '七転び八転がり','phonetic' => 'ななころびはちころがり','url' => 'http://takiya.jp/78/','wikipedia' => ''),
    array('id' => '101','name' => 'ワーナーブラザーズエンターテインメント','acronym' => 'ワーナーブラザーズエンターテインメント','phonetic' => '','url' => '','wikipedia' => ''),
    array('id' => '102','name' => '5bp.','acronym' => '5bp.','phonetic' => '','url' => 'http://5pb.jp/games/','wikipedia' => ''),
    array('id' => '103','name' => 'CHUNSOFT','acronym' => 'チュンソフト','phonetic' => 'ちゅんそふと','url' => 'http://www.chunsoft.jp/','wikipedia' => ''),
    array('id' => '104','name' => 'BOOST ON','acronym' => 'BOOST ON','phonetic' => 'ぶーすとおん','url' => 'http://www.asgard-japan.com/booston/','wikipedia' => ''),
    array('id' => '105','name' => 'Ubisoft','acronym' => 'Ubisoft','phonetic' => 'ゆーびーあいそふと','url' => 'http://www.ubisoft.co.jp/','wikipedia' => '')
);