<?php
return array(
    array('id' => '1','name' => 'カプコン','acronym' => 'カプコン','phonetic' => 'かぷこん','url' => 'http://www.capcom.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '2','name' => 'テクモ','acronym' => 'テクモ','phonetic' => 'てくも','url' => 'http://www.tecmo.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '3','name' => '任天堂','acronym' => '任天堂','phonetic' => 'にんてんどう','url' => 'http://www.nintendo.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '4','name' => 'SCE','acronym' => 'SCE','phonetic' => 'えすしーいー','url' => 'http://www.jp.playstation.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '8','name' => 'フロム・ソフトウェア','acronym' => 'フロム・SW','phonetic' => 'ふろむそふとうぇあ','url' => 'http://www.nouten.com/top.php','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '9','name' => 'EA','acronym' => 'EA','phonetic' => 'いーえー','url' => 'http://www.eajapan.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '10','name' => 'マーベラスエンターテイメント','acronym' => 'マーベラスE','phonetic' => 'まーべらすえんたーていんめんと','url' => 'http://www.mmv.co.jp/game/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '11','name' => 'マイクロソフト','acronym' => 'マイクロソフト','phonetic' => 'まいくろそふと','url' => 'http://www.xbox.com/ja-jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '12','name' => 'セガ','acronym' => 'セガ','phonetic' => 'せが','url' => 'http://sega.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '13','name' => '日本一ソフトウェア','acronym' => '日本一SW','phonetic' => 'にっぽんいちそふとうぇあ','url' => 'http://nippon1.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '14','name' => 'バンダイナムコエンターテインメント','acronym' => 'バンナム','phonetic' => 'ばんだいなむこえんたーていんめんと','url' => 'http://www.bandainamcogames.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '17','name' => 'スクウェア・エニックス','acronym' => 'スクエニ','phonetic' => 'すくうぇあえにっくす','url' => 'http://www.square-enix.com/jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '18','name' => 'タカラ','acronym' => 'タカラ','phonetic' => 'たから','url' => 'http://www.takaratomy.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '19','name' => 'バンダイ','acronym' => 'バンダイ','phonetic' => 'ばんだい','url' => 'http://www.bandai.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '20','name' => 'GAE','acronym' => 'GAE','phonetic' => 'じーえーいー','url' => 'http://www.gae.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '21','name' => 'スパイク','acronym' => 'スパイク','phonetic' => 'すぱいく','url' => 'http://www.spike.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '22','name' => 'コンパイルハート','acronym' => 'コンパイルハート','phonetic' => 'こんぱいるはーと','url' => 'http://www.compileheart.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '23','name' => 'AQインタラクティブ','acronym' => 'AQI','phonetic' => 'えーきゅーいんたらくてぃぶ','url' => 'http://www.aqi.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '24','name' => 'エスコット','acronym' => 'エスコット','phonetic' => '','url' => 'えすこっと','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '25','name' => 'ハドソン','acronym' => 'ハドソン','phonetic' => 'はどそん','url' => 'http://www.hudson.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '26','name' => 'Nibris','acronym' => 'Nibris','phonetic' => 'にぶりす','url' => 'http://www.nibris.net/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '27','name' => 'D3パブリッシャー','acronym' => 'D3P','phonetic' => 'でぃーすりーぱぶりっしゃー','url' => 'http://www.d3p.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '28','name' => 'エニックス','acronym' => 'エニックス','phonetic' => 'えにっくす','url' => 'http://www.square-enix.com/jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '29','name' => 'トンキンハウス','acronym' => 'トンキンハウス','phonetic' => 'とんきんはうす','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '30','name' => 'サミー','acronym' => 'サミー','phonetic' => 'さみー','url' => 'http://www.sammy.co.jp/japanese/index.jsp','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '31','name' => 'アトラス','acronym' => 'アトラス','phonetic' => 'あとらす','url' => 'http://www.atlus.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '32','name' => 'バンプレスト','acronym' => 'バンプレスト','phonetic' => 'ばんぷれすと','url' => 'http://www.banpresto.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '33','name' => 'インターチャネル・ホロン','acronym' => 'ホロン','phonetic' => 'いんたーちゃねるほろん','url' => 'http://www.interchannel.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '34','name' => 'ナウプロダクション','acronym' => 'ナウプロ','phonetic' => 'なうぷろだくしょん','url' => 'http://www.nowpro.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '35','name' => 'メトロ','acronym' => 'メトロ','phonetic' => 'めとろ','url' => 'http://www.metro-japan.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '36','name' => 'アタリ','acronym' => 'アタリ','phonetic' => 'あたり','url' => 'http://www.atarijapan.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '37','name' => 'エクシング','acronym' => 'エクシング','phonetic' => 'えくしんぐ','url' => 'http://www.xing.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '38','name' => 'ポニーキャニオン','acronym' => 'ポニーキャニオン','phonetic' => 'ぽにーきゃにおん','url' => 'http://www.ponycanyon.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '39','name' => 'ディンプル','acronym' => 'ディンプル','phonetic' => 'でぃんぷる','url' => 'http://www.dmpl.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '40','name' => 'アウトブレイク','acronym' => 'アウトブレイク','phonetic' => 'あうとぶれいく','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '41','name' => 'ヒューマン','acronym' => 'ヒューマン','phonetic' => 'ひゅーまん','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '42','name' => 'ビー・ファクトリー','acronym' => 'ビーファク','phonetic' => 'びーふぁくとりー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '43','name' => 'ギャガ・コミュニケーションズ','acronym' => 'ギャガ','phonetic' => 'ぎゃがこみゅにけーしょんず','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '44','name' => 'アクレイムジャパン','acronym' => 'アクレイム','phonetic' => 'あくれいむじゃぱん','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '45','name' => 'ワープ','acronym' => 'ワープ','phonetic' => 'わーぷ','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '46','name' => 'コナミ','acronym' => 'コナミ','phonetic' => 'こなみ','url' => 'http://www.konami.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '47','name' => 'ユタカ','acronym' => 'ユタカ','phonetic' => 'ゆたか','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '48','name' => 'アイディアファクトリー','acronym' => 'アイディアファクトリー','phonetic' => 'あいでぃあふぁくとりー','url' => 'http://www.ideaf.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '49','name' => 'サクセス','acronym' => 'サクセス','phonetic' => 'さくせす','url' => 'http://www.success-corp.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '50','name' => 'クレイジーゲーム','acronym' => 'クレイジーゲーム','phonetic' => 'くれいじーげーむ','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '51','name' => 'ジャレコ','acronym' => 'ジャレコ','phonetic' => 'じゃれこ','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '52','name' => 'メディアエンターテイメント','acronym' => 'メディアE','phonetic' => 'めでぃあえんたーていめんと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '53','name' => 'サイバーフロント','acronym' => 'サイバーフロント','phonetic' => 'さいばーふろんと','url' => 'http://www.cyberfront.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '54','name' => 'ビクターインタラクティブソフトウエア','acronym' => 'ビクター','phonetic' => '','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '55','name' => 'The 3DO Company','acronym' => 'The 3DO Company','phonetic' => 'ざ3でぃーおーかんぱにー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '56','name' => 'ヴィジット','acronym' => 'ヴィジット','phonetic' => 'うぃじっと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '57','name' => 'アイドス','acronym' => 'アイドス','phonetic' => 'あいどす','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '58','name' => '角川書店','acronym' => '角川書店','phonetic' => 'かどかわしょてん','url' => 'http://www.kadokawa.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '59','name' => 'ピーアンドエー','acronym' => 'B&A','phonetic' => 'ぴーあんどえー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '60','name' => 'アクティビジョン','acronym' => 'アクティビジョン','phonetic' => 'あくてぃびじょん','url' => 'http://www.activision.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '61','name' => 'ライブドア','acronym' => 'ライブドア','phonetic' => 'らいぶどあ','url' => 'http://www.livedoor.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '62','name' => 'Sega of America','acronym' => 'Sega(USA)','phonetic' => 'せがおぶあめりか','url' => 'http://www.sega.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '63','name' => 'ソフトマックス','acronym' => 'ソフトマックス','phonetic' => 'そふとまっくす','url' => 'http://www.softmax.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '64','name' => 'インターチャネル','acronym' => 'インターチャネル','phonetic' => 'いんたーちゃんねる','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '65','name' => 'パンドラボックス','acronym' => 'パンドラボックス','phonetic' => 'ぱんどらぼっくす','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '66','name' => 'ジェネックス','acronym' => 'ジェネックス','phonetic' => 'じぇねっくす','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '67','name' => 'アテナ','acronym' => 'アテナ','phonetic' => 'あてな','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '68','name' => 'ソフトバンクBB','acronym' => 'ソフトバンクBB','phonetic' => 'そふとばんくびーびー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '69','name' => 'ズー','acronym' => 'ズー','phonetic' => 'ずー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '70','name' => 'Liar-Soft','acronym' => 'Liar-Soft','phonetic' => 'らいあーそふと','url' => 'http://www.liar.co.jp/index.html','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '71','name' => 'F&C・FC03','acronym' => 'F&C・FC03','phonetic' => 'えふあんどしー','url' => 'http://www.dreamsoft.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '72','name' => 'タイガーマンプロジェクト','acronym' => 'タイガーマン','phonetic' => 'たいがーまんぷろじぇくと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '73','name' => 'アボガドパワーズ','acronym' => 'アボガドパワーズ','phonetic' => 'あぼがどぱわーず','url' => 'http://www.abopa.net/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '74','name' => 'ネル','acronym' => 'ネル','phonetic' => 'ねる','url' => 'http://marigold.1000.tv/nel/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '75','name' => 'Lass','acronym' => 'Lass','phonetic' => 'らす','url' => 'http://lass.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '76','name' => 'ブルーゲイル','acronym' => 'ブルーゲイル','phonetic' => 'ぶるーげいる','url' => 'http://www.bluegale.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '77','name' => 'シーズウェア','acronym' => 'シーズウェア','phonetic' => 'しーずうぇあ','url' => 'http://csware.himeya.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '78','name' => 'MBS Truth','acronym' => 'MBS Truth','phonetic' => 'えむびーえすとぅるーす','url' => 'http://www.teck.co.jp/truth/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '79','name' => 'BLACK CYC','acronym' => 'BLACK CYC','phonetic' => 'ぶらっくさいく','url' => 'http://www.cyc-soft.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '80','name' => '美遊','acronym' => '美遊','phonetic' => 'みゆ','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '81','name' => 'ruf','acronym' => 'ruf','phonetic' => 'らふ','url' => 'http://www.ruf-soft.net/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '82','name' => 'Project-μ','acronym' => 'Project-μ','phonetic' => 'ぷろじぇくとおめが','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '83','name' => 'mirage','acronym' => 'mirage','phonetic' => 'みらーじゅ','url' => 'http://www.mirage-soft.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '84','name' => 'Innocent Grey','acronym' => 'Innocent Grey','phonetic' => 'いのせんとぐれい','url' => 'http://www.gungnir.co.jp/innocentgrey/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '85','name' => 'Candle','acronym' => 'Candle','phonetic' => 'きゃんどる','url' => 'http://www.r18game.com/candle/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '86','name' => 'TOPCAT','acronym' => 'TOPCAT','phonetic' => 'とっぷきゃっと','url' => 'http://www.topcat.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '87','name' => 'ジュエリー','acronym' => 'ジュエリー','phonetic' => 'じゅえりー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '88','name' => 'ニトロプラス','acronym' => 'ニトロプラス','phonetic' => 'にとろぷらす','url' => 'http://www.nitroplus.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '89','name' => 'Leaf','acronym' => 'Leaf','phonetic' => 'りーふ','url' => 'http://leaf.aquaplus.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '90','name' => 'D.O.','acronym' => 'D.O.','phonetic' => 'でぃーおー','url' => 'http://www.do-game.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '91','name' => 'シルキーズ','acronym' => 'シルキーズ','phonetic' => 'しるきーず','url' => 'http://www.silkys.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '92','name' => 'ケロQ','acronym' => 'ケロQ','phonetic' => 'けろきゅー','url' => 'http://www.keroq.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '93','name' => 'Gage','acronym' => 'Gage','phonetic' => 'げーじ','url' => 'http://www.gage-soft.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '94','name' => 'アトリエかぐや','acronym' => 'アトリエかぐや','phonetic' => 'あとりあかぐや','url' => 'http://www.a-kaguya.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '96','name' => 'アルケミスト','acronym' => 'アルケミスト','phonetic' => 'あるけみすと','url' => 'http://www.alchemist-net.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '99','name' => '07th Expansion','acronym' => '07th Expansion','phonetic' => '7えくすぱんしょん','url' => 'http://07th-expansion.net/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '100','name' => '七転び八転がり','acronym' => '七転び八転がり','phonetic' => 'ななころびはちころがり','url' => 'http://takiya.jp/78/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '101','name' => 'ワーナーブラザーズエンターテインメント','acronym' => 'ワーナー','phonetic' => 'わーなーぶらざーずえんたーていんめんと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '102','name' => '5bp.','acronym' => '5bp.','phonetic' => '5びーぴー','url' => 'http://5pb.jp/games/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '103','name' => 'CHUNSOFT','acronym' => 'チュンソフト','phonetic' => 'ちゅんそふと','url' => 'http://www.chunsoft.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '104','name' => 'BOOST ON','acronym' => 'BOOST ON','phonetic' => 'ぶーすとおん','url' => 'http://www.asgard-japan.com/booston/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '105','name' => 'Ubisoft','acronym' => 'UBI','phonetic' => 'ゆーびーあいそふと','url' => 'http://www.ubisoft.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '106','name' => 'Apple','acronym' => 'Apple','phonetic' => 'あっぷる','url' => 'https://www.apple.com/jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%83%E3%83%97%E3%83%AB_(%E4%BC%81%E6%A5%AD)'),
    array('id' => '107','name' => 'aspyr','acronym' => 'aspyr','phonetic' => 'あすぱいやー','url' => 'http://www.aspyr.com/','is_adult_url' => '0','wikipedia' => 'https://en.wikipedia.org/wiki/Aspyr'),
    array('id' => '108','name' => 'DMM GAMES','acronym' => 'DMM','phonetic' => 'でぃーえむえむ','url' => 'http://games.dmm.com/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/DMM.com#DMM_GAMES'),
    array('id' => '109','name' => 'Google','acronym' => 'Google','phonetic' => 'ぐーぐる','url' => 'https://www.google.co.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/Google'),
    array('id' => '110','name' => 'GSC GAME WORLD','acronym' => 'GSC','phonetic' => 'じーえすしーげーむわーるど','url' => 'http://www.gsc-game.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '111','name' => 'IMGN.PRO','acronym' => 'IMGN.PRO','phonetic' => 'あいえむじーえぬぷろ','url' => 'http://imgn.pro/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '112','name' => 'SEEC','acronym' => 'SEEC','phonetic' => 'しーく','url' => 'https://se-ec.co.jp/application-developer-dept/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '113','name' => 'ソニー・インタラクティブエンターテインメント','acronym' => 'SIE','phonetic' => 'そにーいんたらくてぃぶえんたーていんめんと','url' => 'https://www.sie.com/index.html','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%BD%E3%83%8B%E3%83%BC%E3%83%BB%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%82%A8%E3%83%B3%E3%82%BF%E3%83%86%E3%82%A4%E3%83%B3%E3%83%A1%E3%83%B3%E3%83%88'),
    array('id' => '114','name' => 'SKH Apps LLC','acronym' => 'SKH Apps','phonetic' => 'えすけーえいちあぷり','url' => 'http://www.skhapps.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '115','name' => 'Starbreeze','acronym' => 'Starbreeze','phonetic' => 'すたーぶりーず','url' => 'https://www.starbreeze.com/','is_adult_url' => '0','wikipedia' => 'https://en.wikipedia.org/wiki/Starbreeze_Studios'),
    array('id' => '116','name' => 'すたじおみりす','acronym' => 'すたじおみりす','phonetic' => 'すたじおみりす','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%81%99%E3%81%9F%E3%81%98%E3%81%8A%E3%81%BF%E3%82%8A%E3%81%99'),
    array('id' => '117','name' => 'スパイク・チュンソフト','acronym' => 'スパイク・チュンソフト','phonetic' => 'すぱいくちゅんそふと','url' => 'http://www.spike-chunsoft.co.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%91%E3%82%A4%E3%82%AF%E3%83%BB%E3%83%81%E3%83%A5%E3%83%B3%E3%82%BD%E3%83%95%E3%83%88'),
    array('id' => '118','name' => 'パック・イン・ビデオ','acronym' => 'パック・イン・ビデオ','phonetic' => 'ぱっくいんびでお','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%83%E3%82%AF%E3%83%BB%E3%82%A4%E3%83%B3%E3%83%BB%E3%83%93%E3%83%87%E3%82%AA'),
    array('id' => '119','name' => 'アークシステムワークス','acronym' => 'アークSW','phonetic' => 'あーくしすてむわーくす','url' => 'http://www.arcsystemworks.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%BC%E3%82%AF%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%83%AF%E3%83%BC%E3%82%AF%E3%82%B9'),
    array('id' => '120','name' => 'インターグロー','acronym' => 'インターグロー','phonetic' => 'いんたーぐろー','url' => 'http://www.intergrow.co.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%84%E3%82%AF%E3%83%80%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB'),
    array('id' => '121','name' => 'エクスペリエンス','acronym' => 'エクスペリエンス','phonetic' => 'えくすぺりえんす','url' => 'http://www.exp-inc.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%9A%E3%83%AA%E3%82%A8%E3%83%B3%E3%82%B9'),
    array('id' => '122','name' => 'SUNSOFT','acronym' => 'SUNSOFT','phonetic' => 'さんそふと','url' => 'http://www.sun-denshi.co.jp/soft/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%B5%E3%83%B3%E9%9B%BB%E5%AD%90'),
    array('id' => '123','name' => 'ザイザックス','acronym' => 'ZZYZX','phonetic' => 'ざいざっくす','url' => 'http://zzyzx.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '124','name' => 'ツクダシナジー','acronym' => 'ツクダシナジー','phonetic' => 'つくだしなじー','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%84%E3%82%AF%E3%83%80%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB'),
    array('id' => '125','name' => 'ヌードメーカー','acronym' => 'ヌードメーカー','phonetic' => 'ぬーどめーかー','url' => 'http://www.nudemaker.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%8C%E3%83%BC%E3%83%89%E3%83%A1%E3%83%BC%E3%82%AB%E3%83%BC'),
    array('id' => '126','name' => 'ベセスダ・ソフトワークス','acronym' => 'ベセスダ','phonetic' => 'べぜすだ','url' => 'https://bethesda.net/ja/dashboard','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%99%E3%82%BB%E3%82%B9%E3%83%80%E3%83%BB%E3%82%BD%E3%83%95%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%82%B9'),
    array('id' => '127','name' => 'Infinitap Games','acronym' => 'Infinitap','phonetic' => 'いんふぃにたっぷげーむす','url' => 'https://www.infinitapgames.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '128','name' => 'LKA','acronym' => 'LKA','phonetic' => 'えるけーえー','url' => 'http://www.lka.it/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '129','name' => 'Psytec Games','acronym' => 'Psytec Games','phonetic' => 'さいてっくげーむす','url' => 'http://www.psytecgames.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '130','name' => 'レイニーフロッグ','acronym' => 'レイニーフロッグ','phonetic' => 'れいにーふろっぐ','url' => 'http://www.rainyfrog.com/ja','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '131','name' => 'Red Barrels','acronym' => 'Red Barrels','phonetic' => 'れっどばれるす','url' => 'https://redbarrelsgames.com/','is_adult_url' => '0','wikipedia' => 'https://en.wikipedia.org/wiki/Red_Barrels'),
    array('id' => '132','name' => 'TOBE','acronym' => 'TOBE','phonetic' => 'とぅーびー','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '133','name' => 'United Independent Entertainment GmbH','acronym' => 'UIG','phonetic' => 'ゆないてっどいんでぺんでんとえんたーていんめんと','url' => 'http://www.uieg.de/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '134','name' => 'アリエルーフ','acronym' => 'アリエルーフ','phonetic' => 'ありえるーふ','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '135','name' => 'エムスリイエンタテインメント','acronym' => 'M3','phonetic' => 'えむすりいえんたていんめんと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '136','name' => 'クロスファンクション','acronym' => 'クロファン','phonetic' => 'くろすふぁんくしょん','url' => 'http://www.crossfunction.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '137','name' => 'メディアファクトリー','acronym' => 'メディファク','phonetic' => 'めでぃあふぁくとりー','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2%E3%83%95%E3%82%A1%E3%82%AF%E3%83%88%E3%83%AA%E3%83%BC'),
    array('id' => '138','name' => 'Child-Dream','acronym' => 'Child-Dream','phonetic' => 'ちゃいるどどりーむ','url' => 'http://www.child-dream.net/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '139','name' => 'DISTORTION','acronym' => 'DISTORTION','phonetic' => 'でぃすとーしょん','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '140','name' => 'Frictional Games','acronym' => 'Frictional','phonetic' => 'ふりくしょなるげーむす','url' => 'http://www.frictionalgames.com/site/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '141','name' => 'hourglass','acronym' => 'hourglass','phonetic' => 'あわーぐらす','url' => 'http://www.sp-janis.com/hourglass/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '142','name' => 'Mindscape','acronym' => 'Mindscape','phonetic' => 'まいんどすけーぷ','url' => '','is_adult_url' => '0','wikipedia' => 'https://en.wikipedia.org/wiki/Mindscape'),
    array('id' => '143','name' => 'Moon Parrot','acronym' => 'Moon Parrot','phonetic' => 'むーんぱろっと','url' => 'http://www.moonparrot.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '144','name' => 'Sheep','acronym' => 'Sheep','phonetic' => 'しぇーぷ','url' => 'http://www.teck.jp/sheep/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '145','name' => 'SkyFish','acronym' => 'SkyFish','phonetic' => 'すかいふぃっしゅ','url' => 'http://www.sky-fish.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/SkyFish'),
    array('id' => '146','name' => 'Tripwire Interactive','acronym' => 'Tripwire','phonetic' => 'とりっぷわいやいんたらくてぃぶ','url' => 'http://www.tripwireinteractive.com','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '147','name' => 'ZyX','acronym' => 'ZyX','phonetic' => 'じっくす','url' => 'http://www.zyx-game.co.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/ZyX'),
    array('id' => '148','name' => 'あんく','acronym' => 'あんく','phonetic' => 'あんく','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%81%82%E3%82%93%E3%81%8F'),
    array('id' => '149','name' => 'ぴ～にゃん','acronym' => 'ぴ～にゃん','phonetic' => 'ぴ～にゃん','url' => 'http://www.r18game.com/beenyan/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '150','name' => 'アウトリガー工房','acronym' => 'アウトリガー工房','phonetic' => 'あうとりがーこうぼう','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '151','name' => 'サンソフト','acronym' => 'サンソフト','phonetic' => 'さんそふと','url' => 'http://www.sun-denshi.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '152','name' => 'シエラオンライン','acronym' => 'シエラオンライン','phonetic' => 'しえらおんらいん','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%B7%E3%82%A8%E3%83%A9%E3%82%A8%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%86%E3%82%A4%E3%83%B3%E3%83%A1%E3%83%B3%E3%83%88'),
    array('id' => '153','name' => 'シエラ・パイオニア','acronym' => 'シエラ・パイオニア','phonetic' => 'しえらぱいおにあ','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%82%B7%E3%82%A8%E3%83%A9%E3%82%A8%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%86%E3%82%A4%E3%83%B3%E3%83%A1%E3%83%B3%E3%83%88'),
    array('id' => '154','name' => 'セブンエイト','acronym' => 'セブンエイト','phonetic' => 'せぶんえいと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '155','name' => 'ハミングバードソフト','acronym' => 'ハミングバード','phonetic' => 'はみんぐばーどそふと','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%8F%E3%83%9F%E3%83%B3%E3%82%B0%E3%83%90%E3%83%BC%E3%83%89%E3%82%BD%E3%83%95%E3%83%88'),
    array('id' => '156','name' => 'ワンドロー','acronym' => 'ワンドロー','phonetic' => 'わんどろー','url' => 'http://one-draw.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '157','name' => '電脳CLUB','acronym' => '電脳CLUB','phonetic' => 'でんのうくらぶ','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '158','name' => 'TETRATECH','acronym' => 'TETRATECH','phonetic' => 'てとらてっく','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '159','name' => 'ビック東海','acronym' => 'ビック東海','phonetic' => 'びっくとうかい','url' => 'http://www.tokai-com.co.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/TOKAI%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%BA'),
    array('id' => '160','name' => '加賀クリエイト','acronym' => '加賀','phonetic' => 'かがくりえいと','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '161','name' => 'フリュー','acronym' => 'フリュー','phonetic' => 'ふりゅー','url' => 'http://www.furyu.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%95%E3%83%AA%E3%83%A5%E3%83%BC'),
    array('id' => '162','name' => 'Valve','acronym' => 'Valve','phonetic' => 'バルブ','url' => 'http://www.valvesoftware.com/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/Valve_Corporation'),
    array('id' => '163','name' => 'Monolith Productions','acronym' => 'Monolith','phonetic' => 'ものりす','url' => 'https://www.lith.com/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/Monolith_Productions'),
    array('id' => '164','name' => 'キッド','acronym' => 'キッド','phonetic' => 'きっど','url' => '','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/KID_(%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%96%E3%83%A9%E3%83%B3%E3%83%89)'),
    array('id' => '165','name' => 'プリンセスソフト','acronym' => 'プリンセスソフト','phonetic' => 'ぷりんせすそふと','url' => 'http://www.oaks-soft.co.jp/princess-soft/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9%E3%82%BD%E3%83%95%E3%83%88'),
    array('id' => '166','name' => 'Digital Happiness','acronym' => 'Digital Happiness','phonetic' => 'でじたるはぴねす','url' => 'http://digitalhappiness.net/','is_adult_url' => '0','wikipedia' => 'https://en.wikipedia.org/wiki/Digital_Happiness'),
    array('id' => '167','name' => 'アイチェリー','acronym' => 'アイチェリー','phonetic' => 'あいちぇりー','url' => 'http://www.aicherry.com/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '169','name' => 'Palace','acronym' => 'Palace','phonetic' => 'ぱれす','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '170','name' => 'テイクツー・インタラクティブ・ジャパン','acronym' => 'テイクツー','phonetic' => 'ていくつー','url' => 'http://take2games.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%A4%E3%82%AF%E3%83%84%E3%83%BC%E3%83%BB%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96'),
    array('id' => '171','name' => 'テトラ','acronym' => 'テトラ','phonetic' => 'てとら','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '172','name' => 'AMT Savan','acronym' => 'AMT Savan','phonetic' => 'えーえむてぃーさヴぁん','url' => '','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '173','name' => 'Novectacle','acronym' => 'Novectacle','phonetic' => 'のべくたくる','url' => 'http://novect.net/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '174','name' => '言語社','acronym' => '言語社','phonetic' => 'げんごしゃ','url' => 'http://www.gengosha.co.jp/','is_adult_url' => '0','wikipedia' => ''),
    array('id' => '175','name' => 'dramatic create','acronym' => 'dramatic create','phonetic' => 'どらまてぃっくくりえいと','url' => 'http://dramaticcreate.com/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/%E3%83%92%E3%83%A5%E3%83%BC%E3%83%8D%E3%83%83%E3%82%AF%E3%82%B9'),
    array('id' => '176','name' => 'エンターグラム','acronym' => 'エンターグラム','phonetic' => 'えんたーぐらむ','url' => 'http://www.entergram.co.jp/','is_adult_url' => '0','wikipedia' => 'https://ja.wikipedia.org/wiki/TGL')
);
