<?php
return array(
    array('id' =>  '74','name' => '・・・いる！','acronym' => '通常版'),
    array('id' => '400','name' => '『超』怖い話DS 青の章','acronym' => '通常版'),
    array('id' => '496','name' => '@SIMPLE DLシリーズ Vol.5　THE 呪いの廃病院　～閉じ込められた顔のない少女～','acronym' => '通常版'),
    array('id' => '206','name' => '19時03分上野発夜光列車','acronym' => '通常版'),
    array('id' => '207','name' => '19時03分上野発夜行列車 廉価版','acronym' => '廉価版'),
    array('id' => '341','name' => '3days -満ちてゆく刻の彼方で-','acronym' => '通常版'),
    array('id' => '342','name' => '3days -満ちてゆく刻の彼方で- 限定版','acronym' => '限定版'),
    array('id' => '764','name' => '3days リニューアルパッケージ','acronym' => 'リニューアル版'),
    array('id' => '765','name' => '3days -満ちてゆく刻の彼方で- DL版','acronym' => 'DL版'),
    array('id' =>  '10','name' => 'Alan Wake','acronym' => 'XB360版'),
    array('id' => '457','name' => 'Alan Wake','acronym' => 'PC版'),
    array('id' => '861','name' => 'Alan Wake DL版','acronym' => 'XB1 DL版'),
    array('id' => '458','name' => 'Alan Wake プラチナコレクション','acronym' => 'XB360 廉価版'),
    array('id' => '406','name' => 'Alan Wake リミテッド・エディション','acronym' => 'XB360 リミテッド版'),
    array('id' => '430','name' => 'Alice: Madness Returns','acronym' => 'PS3版'),
    array('id' =>  '30','name' => 'Alice: Madness Returns','acronym' => 'PC版'),
    array('id' => '429','name' => 'Alice: Madness Returns','acronym' => 'XB360版'),
    array('id' => '719','name' => 'Alice: Madness Returns','acronym' => 'XB360 廉価版'),
    array('id' => '862','name' => 'Alice: Madness Returns　DL版','acronym' => 'XB1 DL版'),
    array('id' => '587','name' => 'ALIEN: ISOLATION -エイリアン アイソレーション-','acronym' => 'PS4版'),
    array('id' => '588','name' => 'ALIEN: ISOLATION -エイリアン アイソレーション-','acronym' => 'XB1版'),
    array('id' => '841','name' => 'Amnesia: A Machine for Pigs','acronym' => 'Steam版'),
    array('id' => '624','name' => 'Amnesia: The Dark Descent','acronym' => 'Steam版'),
    array('id' => '623','name' => 'Amnesia: The Dark Descent','acronym' => 'パッケージ版'),
    array('id' => '829','name' => 'B～蒼き背徳～','acronym' => '通常版'),
    array('id' => '343','name' => 'BIFRONTE ～公界島奇譚～','acronym' => '通常版'),
    array('id' => '255','name' => 'BIOHAZARD','acronym' => 'PS版'),
    array('id' => '259','name' => 'BIOHAZARD','acronym' => 'PC版'),
    array('id' => '257','name' => 'BIOHAZARD','acronym' => 'SS版'),
    array('id' => '298','name' => 'BIOHAZARD -OUTBREAK File2-','acronym' => '通常版'),
    array('id' => '295','name' => 'BIOHAZARD -OUTBREAK-','acronym' => 'PS2版'),
    array('id' => '296','name' => 'BIOHAZARD -OUTBREAK- Network Adaptor Pack','acronym' => 'Network Adaptor Pack'),
    array('id' => '297','name' => 'BIOHAZARD -OUTBREAK- PlayStation2 the Best','acronym' => 'PlayStation2 the Best'),
    array('id' => '777','name' => 'BIOHAZARD 6 Xbox 360 プラチナコレクション','acronym' => 'XB360 廉価版'),
    array('id' => '778','name' => 'BIOHAZARD 6 PlayStation 3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '774','name' => 'BIOHAZARD 6 Special Package','acronym' => 'SPパッケージ PS3版'),
    array('id' => '775','name' => 'BIOHAZARD 6 Special Package','acronym' => 'SPパッケージ XB360版'),
    array('id' => '776','name' => 'BIOHAZARD Anniversary Package','acronym' => 'アニバーサリーパッケージ PS3版'),
    array('id' => '245','name' => 'biohazard','acronym' => 'Wii版'),
    array('id' => '244','name' => 'biohazard','acronym' => 'GC版'),
    array('id' => '779','name' => 'biohazard Best Price!','acronym' => 'Wii 廉価版'),
    array('id' => '784','name' => 'biohazard Best Price!','acronym' => 'Wii 再廉価版'),
    array('id' => '303','name' => 'BIOHAZARD CODE:Veronica','acronym' => 'DC版'),
    array('id' => '304','name' => 'BIOHAZARD CODE:Veronica 初回限定版','acronym' => 'DC 初回限定版'),
    array('id' => '306','name' => 'BIOHAZARD CODE:Veronica 完全版','acronym' => '完全版 PS2版'),
    array('id' => '311','name' => 'BIOHAZARD CODE:Veronica 完全版','acronym' => '完全版 GC版'),
    array('id' => '305','name' => 'BIOHAZARD CODE:Veronica 完全版','acronym' => '完全版 DC版'),
    array('id' => '894','name' => 'BIOHAZARD CODE:Veronica 完全版','acronym' => '完全版 PS3版'),
    array('id' => '893','name' => 'BIOHAZARD CODE:Veronica 完全版','acronym' => '完全版 ゲームアーカイブス'),
    array('id' => '309','name' => 'BIOHAZARD CODE:Veronica 完全版 Best Price!','acronym' => '完全版 PS2 廉価版'),
    array('id' => '307','name' => 'BIOHAZARD CODE:Veronica 完全版 カプコレ','acronym' => '完全版 PS2 再廉価版'),
    array('id' => '308','name' => 'BIOHAZARD CODE:Veronica 完全版 プレミアムパック','acronym' => '完全版 PS2 プレミアムパック'),
    array('id' => '258','name' => 'BIOHAZARD ディレクターズカット デュアルショックバージョン','acronym' => 'ディレクターズカット デュアルショック版'),
    array('id' => '299','name' => 'BIOHAZARD Deadly Silence','acronym' => '通常版'),
    array('id' => '597','name' => 'BIOHAZARD GAIDEN','acronym' => '通常版'),
    array('id' => '471','name' => 'biohazard HD REMASTER','acronym' => 'PS3版'),
    array('id' => '896','name' => 'biohazard HD REMASTER','acronym' => 'PS4版'),
    array('id' => '897','name' => 'biohazard HD REMASTER','acronym' => 'XB1版'),
    array('id' => '489','name' => 'biohazard ORIGINS COLLECTION','acronym' => 'オリコレ PS4版'),
    array('id' => '490','name' => 'biohazard ORIGINS COLLECTION Best Price!','acronym' => 'オリコレ PS4 廉価版'),
    array('id' => '781','name' => 'biohazard ORIGINS COLLECTION','acronym' => 'オリコレ XB1版'),
    array('id' => '858','name' => 'BIOHAZARD RE:2','acronym' => 'XB1版'),
    array('id' => '857','name' => 'BIOHAZARD RE:2','acronym' => 'PS4版'),
    array('id' => '859','name' => 'BIOHAZARD RE:2','acronym' => 'PC版'),
    array('id' => '424','name' => 'BIOHAZARD REVELATIONS','acronym' => '3DS版'),
    array('id' => '790','name' => 'BIOHAZARD REVELATIONS2 Best Price','acronym' => 'PS4 廉価版'),
    array('id' => '425','name' => 'BIOHAZARD REVIVAL SELECTION','acronym' => 'リバイバルセレクション XB360版'),
    array('id' => '426','name' => 'BIOHAZARD REVIVAL SELECTION','acronym' => 'リバイバルセレクション PS3版'),
    array('id' => '890','name' => 'BIOHAZARD ディレクターズカット','acronym' => 'ディレクターズカット ゲームアーカイブス'),
    array('id' => '256','name' => 'BIOHAZARD ディレクターズカット','acronym' => 'ディレクターズカット PS版'),
    array('id' => '247','name' => 'biohazard0','acronym' => 'Wii版'),
    array('id' => '246','name' => 'biohazard0','acronym' => 'GC版'),
    array('id' => '474','name' => 'biohazard0 HD REMASTER','acronym' => 'PS3版'),
    array('id' => '478','name' => 'biohazard0 HD REMASTER','acronym' => 'PC版'),
    array('id' => '477','name' => 'biohazard0 HD REMASTER','acronym' => 'XB1版'),
    array('id' => '476','name' => 'biohazard0 HD REMASTER','acronym' => 'PS4版'),
    array('id' => '267','name' => 'BIOHAZARD2','acronym' => 'GC版'),
    array('id' => '264','name' => 'BIOHAZARD2','acronym' => 'PS版'),
    array('id' => '891','name' => 'BIOHAZARD2','acronym' => 'ゲームアーカイブス'),
    array('id' => '266','name' => 'BIOHAZARD2','acronym' => 'N64版'),
    array('id' => '268','name' => 'BIOHAZARD2 Value Plus','acronym' => 'DC 廉価版'),
    array('id' => '265','name' => 'BIOHAZARD2 デュアルショックバージョン','acronym' => 'PS デュアルショック版'),
    array('id' => '293','name' => 'BIOHAZARD3 -LAST ESCAPE-','acronym' => 'DC版'),
    array('id' => '291','name' => 'BIOHAZARD3 -LAST ESCAPE-','acronym' => 'PS版'),
    array('id' => '294','name' => 'BIOHAZARD3 -LAST ESCAPE-','acronym' => 'GC版'),
    array('id' => '892','name' => 'BIOHAZARD3 -LAST ESCAPE-','acronym' => 'ゲームアーカイブス'),
    array('id' => '292','name' => 'BIOHAZARD3 -LAST ESCAPE- カプコレ','acronym' => 'PS 廉価版'),
    array('id' => '481','name' => 'biohazard4','acronym' => 'XB1版'),
    array('id' => '895','name' => 'biohazard4','acronym' => 'PS3版'),
    array('id' => '313','name' => 'biohazard4','acronym' => 'PS2版'),
    array('id' => '315','name' => 'biohazard4','acronym' => 'PC版'),
    array('id' => '312','name' => 'biohazard4','acronym' => 'GC版'),
    array('id' => '314','name' => 'biohazard4 PlayStation2 the Best','acronym' => 'PS2 廉価版'),
    array('id' => '316','name' => 'biohazard4 Wii Edition','acronym' => 'Wii版'),
    array('id' =>  '47','name' => 'BIOHAZARD5','acronym' => 'XB360版'),
    array('id' => '484','name' => 'BIOHAZARD5','acronym' => 'XB1版'),
    array('id' =>  '16','name' => 'BIOHAZARD5','acronym' => 'PC版'),
    array('id' =>  '46','name' => 'BIOHAZARD5','acronym' => 'PS3版'),
    array('id' => '796','name' => 'BIOHAZARD5 Xbox360 プラチナコレクション','acronym' => 'XB360 廉価版'),
    array('id' =>  '48','name' => 'BIOHAZARD5 Deluxe Edition','acronym' => 'XB360 デラックス版'),
    array('id' => '794','name' => 'BIOHAZARD5 オルタナティブ エディション PlayStation 3 the Best','acronym' => 'AE PS3 廉価版'),
    array('id' => '396','name' => 'BIOHAZARD5 オルタナティブエディション','acronym' => 'AE PS3版'),
    array('id' => '487','name' => 'BIOHAZARD6','acronym' => 'XB1版'),
    array('id' => '454','name' => 'BIOHAZARD6','acronym' => 'PS3版'),
    array('id' => '453','name' => 'BIOHAZARD6','acronym' => 'XB360版'),
    array('id' => '488','name' => 'BIOHAZARD7 -Resident Evil-','acronym' => 'PS4版'),
    array('id' => '696','name' => 'BIOHAZARD7 -Resident Evil-','acronym' => 'PC版'),
    array('id' => '692','name' => 'BIOHAZARD7 -Resident Evil-','acronym' => 'XB1版'),
    array('id' => '848','name' => 'BIOHAZARD7 -Resident Evil- クラウドバージョン','acronym' => 'Switch版'),
    array('id' => '693','name' => 'BIOHAZARD7 -Resident Evil- グロテスク ver.','acronym' => 'グロテスク XB1版'),
    array('id' => '689','name' => 'BIOHAZARD7 -Resident Evil- グロテスク ver.','acronym' => 'グロテスク PS4版'),
    array('id' => '694','name' => 'BIOHAZARD7 -Resident Evil- ゴールドエディション','acronym' => 'GE XB1版'),
    array('id' => '690','name' => 'BIOHAZARD7 -Resident Evil- ゴールドエディション','acronym' => 'GE PS4版'),
    array('id' => '695','name' => 'BIOHAZARD7 -Resident Evil- ゴールドエディション グロテスク ver.','acronym' => 'GE グロテスク XB1版'),
    array('id' => '691','name' => 'BIOHAZARD7 -Resident Evil- ゴールドエディション グロテスク ver.','acronym' => 'GE グロテスク PS4版'),
    array('id' => '323','name' => 'BS探偵倶楽部 雪に消えた過去 中編','acronym' => '中編'),
    array('id' => '322','name' => 'BS探偵倶楽部 雪に消えた過去 前編','acronym' => '前編'),
    array('id' => '324','name' => 'BS探偵倶楽部 雪に消えた過去 後編','acronym' => '後編'),
    array('id' =>   '7','name' => 'CALLING～黒き着信～','acronym' => '通常版'),
    array('id' => '107','name' => 'CARRIER','acronym' => 'DC'),
    array('id' => '847','name' => 'CLOSED NIGHTMARE','acronym' => 'Switch版'),
    array('id' => '846','name' => 'CLOSED NIGHTMARE','acronym' => 'PS4版'),
    array('id' => '161','name' => 'CONDEMNED:PSYCHO CRIME','acronym' => '通常版'),
    array('id' => '162','name' => 'Condemned2: Bloodshot 輸入版','acronym' => 'PS3版'),
    array('id' => '163','name' => 'Condemned2: Bloodshot 輸入版','acronym' => 'XB360版'),
    array('id' => '569','name' => 'Crystal Rift','acronym' => 'PC版'),
    array('id' => '568','name' => 'Crystal Rift','acronym' => 'PS4版'),
    array('id' => '366','name' => 'D.O.Classic Vol.1 「雑音領域」','acronym' => 'D.O.Classic'),
    array('id' => '771','name' => 'D\'ERLANGER 〜誘惑の淫魔病棟〜 DL版','acronym' => 'PC DL版'),
    array('id' => '639','name' => 'D\'ERLANGER ～誘惑の淫魔病棟～','acronym' => 'PC版'),
    array('id' => '640','name' => 'D\'ERLANGER ～誘惑の淫魔病棟～','acronym' => 'DVD-PG版'),
    array('id' => '217','name' => 'DARK TALES From The Lost Soul','acronym' => '通常版'),
    array('id' => '215','name' => 'darkSector','acronym' => 'PS3版'),
    array('id' => '216','name' => 'darkSector','acronym' => 'XB360版'),
    array('id' => '211','name' => 'DARKSEED','acronym' => 'PS版'),
    array('id' => '213','name' => 'DARKSEED','acronym' => 'SS版'),
    array('id' => '214','name' => 'DARKSEEDII','acronym' => 'SS版'),
    array('id' => '212','name' => 'DARKSEEDII','acronym' => 'PS版'),
    array('id' => '570','name' => 'DAYLIGHT','acronym' => '通常版'),
    array('id' => '491','name' => 'Dead By Daylight','acronym' => 'PC版'),
    array('id' => '688','name' => 'Dead By Daylight 北米版','acronym' => 'XB1版'),
    array('id' => '448','name' => 'DEAD ISLAND','acronym' => 'PC版'),
    array('id' => '449','name' => 'DEAD ISLAND','acronym' => 'XB360版'),
    array('id' => '450','name' => 'DEAD ISLAND','acronym' => 'PS3版'),
    array('id' => '917','name' => 'Dead Island Definitive Edition','acronym' => 'Definitive Edition Steam版'),
    array('id' => '532','name' => 'Dead Island: Riptide','acronym' => 'XB360版'),
    array('id' => '531','name' => 'Dead Island: Riptide','acronym' => 'PS3版'),
    array('id' => '918','name' => 'Dead Island: Riptide Definitive Edition','acronym' => 'Definitive Edition Steam版'),
    array('id' => '530','name' => 'DEAD ISLAND: Zombie of the Year Edition','acronym' => 'ゾンビオブザイヤー XB360版'),
    array('id' => '529','name' => 'DEAD ISLAND: Zombie of the Year Edition','acronym' => 'ゾンビオブザイヤー PS3版'),
    array('id' => '527','name' => 'DEAD ISLAND: ダブルゾンビパック','acronym' => 'ダブルゾンビパック PS3版'),
    array('id' => '528','name' => 'DEAD ISLAND: ディフィニティブコレクション','acronym' => 'ディフィニティブコレクション PS4版'),
    array('id' => '685','name' => 'Dead Space','acronym' => 'PC版'),
    array('id' => '251','name' => 'Dead Space 輸入版','acronym' => 'XB360版'),
    array('id' => '252','name' => 'Dead Space 輸入版','acronym' => 'PS3版'),
    array('id' => '521','name' => 'DEAD SPACE2','acronym' => 'PS3版'),
    array('id' => '522','name' => 'DEAD SPACE2','acronym' => 'XB360版'),
    array('id' => '523','name' => 'DEAD SPACE2','acronym' => 'PC版'),
    array('id' => '525','name' => 'DEAD SPACE3','acronym' => 'XB360版'),
    array('id' => '526','name' => 'DEAD SPACE3','acronym' => 'PC版'),
    array('id' => '524','name' => 'DEAD SPACE3','acronym' => 'PS3版'),
    array('id' => '908','name' => 'Deadly Premonition　レッドシーズプロファイル　コンプリートエディション','acronym' => 'PS3 DL版'),
    array('id' => '227','name' => 'DEEP FEAR','acronym' => '通常版'),
    array('id' => '237','name' => 'DEMENTIUM-閉鎖病棟-','acronym' => 'DS版'),
    array('id' => '225','name' => 'DEMENTO','acronym' => 'PS2版'),
    array('id' => '686','name' => 'DEMENTO','acronym' => 'PS3版'),
    array('id' => '226','name' => 'DEMENTO カプコレ','acronym' => 'PS2 廉価版'),
    array('id' => '288','name' => 'DINO CRISIS','acronym' => 'PS版'),
    array('id' => '290','name' => 'DINO CRISIS','acronym' => 'DC版'),
    array('id' => '888','name' => 'DINO CRISIS','acronym' => 'ゲームアーカイブス'),
    array('id' => '289','name' => 'DINO CRISIS PlayStation the Best ','acronym' => 'PS 廉価版'),
    array('id' => '344','name' => 'DIVI-DEAD','acronym' => '通常版'),
    array('id' => '770','name' => 'DIVI-DEAD DL版','acronym' => 'DL版'),
    array('id' => '345','name' => 'DOOP','acronym' => '通常版'),
    array('id' => '346','name' => 'DOOP ADVANCE','acronym' => 'ADVANCE'),
    array('id' => '772','name' => 'DOOP ADVANCE DL版','acronym' => 'ADVANCE DL版'),
    array('id' => '798','name' => 'DreadEye VR','acronym' => '通常版'),
    array('id' => '716','name' => 'DreadOut','acronym' => '通常版'),
    array('id' => '717','name' => 'DreadOut Deluxe Pack','acronym' => 'デラックスパック'),
    array('id' => '718','name' => 'DreadOut: Keepers of The Dark','acronym' => '通常版'),
    array('id' => '463','name' => 'Dの食卓','acronym' => '3DO版'),
    array('id' => '465','name' => 'Dの食卓 COMPLETE GRAPHICS PlayStation the Best','acronym' => 'PS 廉価版'),
    array('id' => '466','name' => 'Dの食卓 コンプリートグラフィックス','acronym' => 'PS版'),
    array('id' => '464','name' => 'Dの食卓 ディレクターズカット','acronym' => '3DO ディレクターズカット版'),
    array('id' => '231','name' => 'Dの食卓2','acronym' => '通常版'),
    array('id' => '720','name' => 'EA BEST HITS Alice: Madness Returns','acronym' => 'PS3 廉価版'),
    array('id' => '740','name' => 'EA BEST HITS シャドウ オブ ザ ダムド','acronym' => 'PS3 廉価版'),
    array('id' =>  '29','name' => 'EA BEST SELECTIONS アリス・イン・ナイトメア','acronym' => '廉価版'),
    array('id' => '492','name' => 'Emily Wants to Play','acronym' => 'Steam版'),
    array('id' => '493','name' => 'Emily Wants to Play','acronym' => 'iOS版'),
    array('id' => '494','name' => 'Emily Wants to Play','acronym' => 'PS4版'),
    array('id' =>  '81','name' => 'es','acronym' => '通常版'),
    array('id' => '339','name' => 'Esの方程式 DOS/V版','acronym' => 'DOS/V版'),
    array('id' => '338','name' => 'Esの方程式 PC-9801版','acronym' => 'PC-9801版'),
    array('id' => '340','name' => 'Esの方程式 Windows 95/98版','acronym' => 'Windows 95/98版'),
    array('id' => '823','name' => 'Esの方程式 Wo Es war, soll Ich werden. DL版','acronym' => 'DL版'),
    array('id' => '747','name' => 'EXTRAVAGANZA 〜蟲愛でる少女〜 Windows8.1動作版 DL版','acronym' => 'Win8.1動作版 DL版'),
    array('id' => '347','name' => 'EXTRAVAGANZA ～蟲愛でる少女～','acronym' => 'PC版'),
    array('id' => '348','name' => 'EXTRAVAGANZA ～蟲愛でる少女～ 初回特典版','acronym' => 'PC 初回特典版'),
    array('id' => '746','name' => 'EXTRAVAGANZA ～蟲愛でる少女～ DVD-PG版','acronym' => 'DVD-PG版'),
    array('id' => '745','name' => 'EXTRAVAGANZA ～蟲愛でる少女～ Windows7対応版','acronym' => 'PC Win7対応版'),
    array('id' => '704','name' => 'F.E.A.R. 輸入版','acronym' => 'XB360版'),
    array('id' => '703','name' => 'F.E.A.R. 輸入版','acronym' => 'PS3版'),
    array('id' =>   '2','name' => 'F.E.A.R.2 -Project Origin-','acronym' => 'XB360版'),
    array('id' =>   '1','name' => 'F.E.A.R.2 -Project Origin-','acronym' => 'PS3版'),
    array('id' => '702','name' => 'F.E.A.R.3','acronym' => 'Steam版'),
    array('id' => '432','name' => 'F.E.A.R.3','acronym' => 'PS3版'),
    array('id' => '701','name' => 'F.E.A.R.3','acronym' => 'PC パッケージ版'),
    array('id' => '431','name' => 'F.E.A.R.3','acronym' => 'XB360版'),
    array('id' =>  '34','name' => 'FATAL FRAME -零SPECIAL EDITION-','acronym' => 'XB版'),
    array('id' =>  '37','name' => 'FATAL FRAME II Crimson Butterfly','acronym' => 'XB版'),
    array('id' => '625','name' => 'innocence pain ～満ちる闇　欠ける月～','acronym' => 'PC版'),
    array('id' => '727','name' => 'innocence pain ～満ちる闇　欠ける月～ DL版','acronym' => 'PC DL版'),
    array('id' => '726','name' => 'innocence pain ～満ちる闇　欠ける月～ DVD-PG版','acronym' => 'DVD-PG版'),
    array('id' => '204','name' => 'Juggernaut～戦慄の扉～','acronym' => '通常版'),
    array('id' => '549','name' => 'KHOLAT','acronym' => 'Steam版'),
    array('id' => '628','name' => 'Killing Floor2','acronym' => 'PC版'),
    array('id' => '916','name' => 'Killing Floor2 Limited Edition 輸入版','acronym' => 'PC版 Limited Edition'),
    array('id' => '629','name' => 'Killing Floor2 輸入版','acronym' => 'PS4版'),
    array('id' => '630','name' => 'Killing Floor2 輸入版','acronym' => 'XB1版'),
    array('id' => '125','name' => 'LAST WHISPER','acronym' => '通常版'),
    array('id' => '126','name' => 'LAST WHISPER ベストプライス アウトブレイクコレクション','acronym' => '廉価版'),
    array('id' => '508','name' => 'Layers of Fear','acronym' => 'PS4版'),
    array('id' => '915','name' => 'Layers of Fear','acronym' => 'XB1版'),
    array('id' => '507','name' => 'Layers of Fear','acronym' => 'PC版'),
    array('id' => '909','name' => 'Left 4 Dead DL版','acronym' => 'XB1版'),
    array('id' => '43','name' => 'Left 4 Dead GAME OF THE YEAR EDITION','acronym' => 'PC GOTY版'),
    array('id' => '664','name' => 'Liar-soft Selection 19 『漆黒のシャルノス -What a beautiful Tomorrow- Fullvoice ReBORN』','acronym' => 'ReBORN 廉価版'),
    array('id' => '700','name' => 'LITTLE NIGHTMARES -リトルナイトメア- デラックスエディション','acronym' => 'DXエディション Switch版'),
    array('id' => '699','name' => 'LITTLE NIGHTMARES -リトルナイトメア- デラックスエディション','acronym' => 'DXエディション PS4版'),
    array('id' => '599','name' => 'LITTLE NIGHTMARES-リトルナイトメア-','acronym' => 'PC版'),
    array('id' => '600','name' => 'LITTLE NIGHTMARES-リトルナイトメア-','acronym' => 'PS4版'),
    array('id' => '349','name' => 'Love Letter','acronym' => 'PC版'),
    array('id' => '818','name' => 'Love Letter DL版','acronym' => 'PC DL版'),
    array('id' => '817','name' => 'Love Letter DVD-PG版','acronym' => 'DVD-PG版'),
    array('id' => '146','name' => 'michigan','acronym' => '通常版'),
    array('id' => '632','name' => 'Mirage～淫宴の触手病棟～ Another Story Of D\'ERLANGER','acronym' => 'DVD-PG版'),
    array('id' => '631','name' => 'Mirage～淫宴の触手病棟～ Another Story Of D\'ERLANGER','acronym' => 'PC版'),
    array('id' => '232','name' => 'NEBULA -ECHO NIGHT-','acronym' => '通常版'),
    array('id' => '229','name' => 'Necro-Nesia','acronym' => '通常版'),
    array('id' => '856','name' => 'NG','acronym' => '通常版'),
    array('id' => '495','name' => 'Night Cry','acronym' => 'Steam版'),
    array('id' => '571','name' => 'Night Walker','acronym' => '通常版'),
    array('id' => '849','name' => 'NightCry','acronym' => 'Vita版'),
    array('id' => '572','name' => 'One\'s Own [or very]','acronym' => '通常版'),
    array('id' => '575','name' => 'OUTLAST','acronym' => 'XB1版'),
    array('id' => '573','name' => 'OUTLAST','acronym' => 'PC版'),
    array('id' => '574','name' => 'OUTLAST','acronym' => 'PS4版'),
    array('id' => '578','name' => 'OUTLAST 2','acronym' => 'XB1版'),
    array('id' => '576','name' => 'OUTLAST 2','acronym' => 'PC版'),
    array('id' => '577','name' => 'OUTLAST 2','acronym' => 'PS4版'),
    array('id' => '579','name' => 'Pineview Drive - House of Horror','acronym' => '通常版'),
    array('id' =>  '83','name' => 'R?MJ THE MYSTERY HOSPITAL','acronym' => 'PS版'),
    array('id' =>  '84','name' => 'R?MJ THE MYSTERY HOSPITAL','acronym' => 'SS版'),
    array('id' =>  '85','name' => 'R?MJ THE MYSTERY HOSPITAL PlayStation the Best','acronym' => 'PS 廉価版'),
    array('id' =>   '8','name' => 'Red Seeds Profile -レッドシーズプロファイル-','acronym' => 'XB360版'),
    array('id' =>   '9','name' => 'Red Seeds Profile -レッドシーズプロファイル-','acronym' => 'PS3版'),
    array('id' => '845','name' => 'RESISTANCE -アメリカ最後の抵抗-','acronym' => '通常版'),
    array('id' => '844','name' => 'RESISTANCE 3','acronym' => '通常版'),
    array('id' =>  '54','name' => 'RESISTANCE～人類没落の日～','acronym' => '通常版'),
    array('id' =>  '55','name' => 'RESISTANCE～人類没落の日～ PlayStation3 the Best','acronym' => 'PlayStation3 the Best'),
    array('id' =>  '57','name' => 'RESISTANCE～報復の刻～','acronym' => '通常版'),
    array('id' =>  '56','name' => 'RESISTANCE2','acronym' => '通常版'),
    array('id' => '437','name' => 'Rise of Nightmares','acronym' => '通常版'),
    array('id' => '124','name' => 'RUN LIKE HELL','acronym' => '通常版'),
    array('id' => '520','name' => 'S.T.A.L.K.E.R.: Call of Pripyat','acronym' => 'Steam版'),
    array('id' => '519','name' => 'S.T.A.L.K.E.R.: Clear Sky','acronym' => 'Steam版'),
    array('id' => '518','name' => 'S.T.A.L.K.E.R.: Shadow of Chernobyl','acronym' => 'Steam版'),
    array('id' => '709','name' => 'S.T.A.L.K.E.R.: Shadow of Chernobyl 日本語マニュアル付 英語版','acronym' => 'パッケージ版'),
    array('id' => '209','name' => 'SAINTS 聖なる魔物','acronym' => '通常版'),
    array('id' => '581','name' => 'SAW','acronym' => 'PC版'),
    array('id' => '580','name' => 'SAW','acronym' => 'PS3版'),
    array('id' => '583','name' => 'SAW II: Flesh & Blood','acronym' => 'XB360版'),
    array('id' => '582','name' => 'SAW II: Flesh & Blood','acronym' => 'PS3版'),
    array('id' => '105','name' => 'SEGA THE BEST かまいたちの夜2 特別篇','acronym' => 'PSP 廉価版'),
    array('id' => '710','name' => 'SHADOW AND SHADOW','acronym' => 'PS版'),
    array('id' => '398','name' => 'SILENT HILL -SHATTERED MEMORIES-','acronym' => 'PSP版'),
    array('id' => '397','name' => 'SILENT HILL -SHATTERED MEMORIES-','acronym' => 'Wii版'),
    array('id' => '399','name' => 'SILENT HILL -SHATTERED MEMORIES-','acronym' => 'PS2版'),
    array('id' => '824','name' => 'SILENT HILL -SHATTERED MEMORIES- ベストセレクション','acronym' => 'PSP 廉価版'),
    array('id' => '827','name' => 'SILENT HILL : Book Of Memories','acronym' => '通常版'),
    array('id' => '470','name' => 'SILENT HILL: DOWNPOUR','acronym' => '通常版'),
    array('id' => '459','name' => 'SILENT HILL: HD EDITION','acronym' => 'PS3版'),
    array('id' => '187','name' => 'Silent Hill: Homecoming (輸入版)','acronym' => 'XB360版'),
    array('id' => '186','name' => 'Silent Hill: Homecoming (輸入版)','acronym' => 'PS3版'),
    array('id' => '879','name' => 'SIREN','acronym' => 'ゲームアーカイブス'),
    array('id' => '165','name' => 'SIREN','acronym' => 'PS2版'),
    array('id' => '166','name' => 'SIREN PlayStation 2 the Best','acronym' => 'PS2 廉価版'),
    array('id' => '167','name' => 'SIREN PlayStation 2 the Best ','acronym' => 'PS2 再廉価版'),
    array('id' => '171','name' => 'SIREN:New Translation PlayStation 3 the Best','acronym' => 'PlayStation 3 the Best'),
    array('id' => '170','name' => 'SIREN:New Translation','acronym' => '通常版'),
    array('id' => '168','name' => 'SIREN2','acronym' => '通常版'),
    array('id' => '169','name' => 'SIREN2 PlayStation 2 the Best','acronym' => 'PlayStation 2 the Best'),
    array('id' =>  '19','name' => 'SuperLite 2000 アドベンチャー アオイシロ','acronym' => 'PS2 廉価版'),
    array('id' =>  '22','name' => 'SuperLite2000 アドベンチャー アカイイト','acronym' => '廉価版'),
    array('id' =>  '11','name' => 'The 3rd Birthday','acronym' => '通常版'),
    array('id' => '189','name' => 'THE DARKNESS','acronym' => 'XB360版'),
    array('id' => '190','name' => 'THE DARKNESS','acronym' => 'PS3版'),
    array('id' => '800','name' => 'THE DARKNESS II','acronym' => 'XB360版'),
    array('id' => '799','name' => 'THE DARKNESS II','acronym' => 'PS3版'),
    array('id' => '801','name' => 'THE DARKNESS II DL版','acronym' => 'PC DL版'),
    array('id' => '194','name' => 'The FEAR','acronym' => '通常版'),
    array('id' => '620','name' => 'The Inpatient -闇の病棟-','acronym' => '通常版'),
    array('id' => '551','name' => 'The Last of Us','acronym' => 'PS3版'),
    array('id' => '828','name' => 'The Last of Us Part II','acronym' => 'PS4版'),
    array('id' => '552','name' => 'The Last of Us PlayStation3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '553','name' => 'The Last of Us Remastered','acronym' => 'PS4版'),
    array('id' => '197','name' => 'the Ring','acronym' => '通常版'),
    array('id' => '584','name' => 'The Town of Light','acronym' => 'PC版'),
    array('id' => '585','name' => 'The Town of Light','acronym' => 'PS4版'),
    array('id' => '586','name' => 'The Town of Light','acronym' => 'XB1版'),
    array('id' => '188','name' => 'THE ゾンビV.S.救急車','acronym' => '通常版'),
    array('id' => '192','name' => 'THE 呪いのゲーム','acronym' => '通常版'),
    array('id' => '191','name' => 'THE 大量地獄','acronym' => '通常版'),
    array('id' => '195','name' => 'THEホラーミステリー～惨劇館ケビン伯爵の復活～','acronym' => '通常版'),
    array('id' => '881','name' => 'THEホラーミステリー～惨劇館ケビン伯爵の復活～','acronym' => 'ゲームアーカイブス'),
    array('id' => '193','name' => 'THE廃屋病棟～呪われた病院からの脱出～','acronym' => '通常版'),
    array('id' => '198','name' => 'THE恋愛ホラーアドベンチャー-漂流少女-','acronym' => '通常版'),
    array('id' => '260','name' => 'Ultra2000 バイオハザード','acronym' => 'PC 廉価版'),
    array('id' => '497','name' => 'Until Dawn - 惨劇の山荘 -','acronym' => '通常版'),
    array('id' => '852','name' => 'WARNER THE BEST フィアー3','acronym' => 'PS3 廉価版'),
    array('id' => '499','name' => 'WHITEDAY～学校という名の迷宮～','acronym' => '通常版'),
    array('id' =>  '17','name' => 'アオイシロ','acronym' => 'PS2版'),
    array('id' =>  '20','name' => 'アオイシロ','acronym' => 'PC版'),
    array('id' =>  '18','name' => 'アオイシロ 限定版 ','acronym' => 'PS2 限定版'),
    array('id' =>  '21','name' => 'アカイイト','acronym' => '通常版'),
    array('id' => '860','name' => 'アカイイト','acronym' => 'ゲームアーカイブス'),
    array('id' =>  '26','name' => 'あかずの間','acronym' => '通常版'),
    array('id' =>  '27','name' => 'あかずの間 廉価版 ','acronym' => '廉価版'),
    array('id' => '352','name' => 'アノニマス','acronym' => '通常版'),
    array('id' =>  '28','name' => 'アリス・イン・ナイトメア','acronym' => '通常版'),
    array('id' => '738','name' => 'アルティメットヒッツ The 3rd Birthday','acronym' => '廉価版'),
    array('id' =>  '50','name' => 'アローン・イン・ザ・ダーク','acronym' => 'PC版'),
    array('id' =>  '31','name' => 'アローン・イン・ザ・ダーク','acronym' => '通常版'),
    array('id' =>  '49','name' => 'アローン・イン・ザ・ダーク','acronym' => 'PS3版'),
    array('id' =>  '51','name' => 'アローン・イン・ザ・ダーク','acronym' => 'XB360版'),
    array('id' => '832','name' => 'アローン・イン・ザ・ダーク ～新たなる悪夢～','acronym' => '通常版'),
    array('id' => '405','name' => 'アローン・イン・ザ・ダーク2','acronym' => '3DO版'),
    array('id' => '404','name' => 'アローン・イン・ザ・ダーク2','acronym' => 'SS版'),
    array('id' => '403','name' => 'アローン・イン・ザ・ダーク2','acronym' => 'PS版'),
    array('id' => '831','name' => 'アローン・イン・ザ・ダーク3 DOS/V版','acronym' => 'DOS/V版'),
    array('id' => '830','name' => 'アローン・イン・ザ・ダーク3 Windows版','acronym' => 'Windows版'),
    array('id' => '409','name' => 'イケニエノヨル','acronym' => '通常版'),
    array('id' =>  '75','name' => 'イルブリード','acronym' => '通常版'),
    array('id' => '238','name' => 'ヴァンパイア・レイン','acronym' => 'XB360版'),
    array('id' => '239','name' => 'ヴァンパイア・レイン～アルダート・スピーシーズ～','acronym' => 'PS3版'),
    array('id' => '422','name' => 'うみねこのなく頃に ～魔女と推理の輪舞曲～','acronym' => 'PS3版'),
    array('id' => '442','name' => 'うみねこのなく頃にPortable 1','acronym' => 'Portable 1'),
    array('id' => '443','name' => 'うみねこのなく頃にPortable 2','acronym' => 'Portable 2'),
    array('id' => '822','name' => 'うみねこのなく頃に','acronym' => '通常版'),
    array('id' => '821','name' => 'うみねこのなく頃に〜うみねこセット〜','acronym' => 'うみねこセット'),
    array('id' => '446','name' => 'うみねこのなく頃に散　～真実と幻想の夜想曲～','acronym' => 'PS3版'),
    array('id' => '447','name' => 'うみねこのなく頃に散　～真実と幻想の夜想曲～ (限定版)','acronym' => 'PS3 限定版'),
    array('id' => '863','name' => 'エコーナイト','acronym' => 'ゲームアーカイブス'),
    array('id' =>  '76','name' => 'エコーナイト','acronym' => '通常版'),
    array('id' =>  '77','name' => 'エコーナイト PlayStation the Best','acronym' => 'PlayStation the Best'),
    array('id' =>  '78','name' => 'エコーナイト PS One Books','acronym' => 'PS One Books'),
    array('id' => '864','name' => 'エコーナイト#2 眠りの支配者','acronym' => 'ゲームアーカイブス'),
    array('id' =>  '79','name' => 'エコーナイト#2 眠りの支配者','acronym' => '通常版'),
    array('id' =>  '80','name' => 'エコーナイト#2 眠りの支配者 PS one Books','acronym' => 'PS One Books'),
    array('id' =>  '82','name' => 'エターナル・ダークネス','acronym' => '通常版'),
    array('id' => '235','name' => 'おおかみかくし','acronym' => '通常版'),
    array('id' => '589','name' => 'カース ザ・アイ・オブ・イシス','acronym' => '通常版'),
    array('id' => '502','name' => 'かまいたちの夜','acronym' => 'Android版'),
    array('id' =>  '97','name' => 'かまいたちの夜','acronym' => 'SFC版'),
    array('id' => '100','name' => 'かまいたちの夜 ADVANCE','acronym' => 'GBA版'),
    array('id' => '872','name' => 'かまいたちの夜 VC版','acronym' => 'WiiU VC版'),
    array('id' => '871','name' => 'かまいたちの夜 VC版','acronym' => 'Wii VC版'),
    array('id' =>  '98','name' => 'かまいたちの夜 特別篇','acronym' => 'PS版'),
    array('id' => '873','name' => 'かまいたちの夜 特別篇','acronym' => 'ゲームアーカイブス'),
    array('id' =>  '99','name' => 'かまいたちの夜 特別篇 PlayStation The Best','acronym' => 'PS 廉価版'),
    array('id' => '834','name' => 'かまいたちの夜 輪廻彩声','acronym' => 'PC版'),
    array('id' => '833','name' => 'かまいたちの夜 輪廻彩声','acronym' => 'Vita版'),
    array('id' => '106','name' => 'かまいたちの夜×3 三日月島事件の真相','acronym' => '通常版'),
    array('id' => '104','name' => 'かまいたちの夜2 特別篇','acronym' => 'PSP版'),
    array('id' => '101','name' => 'かまいたちの夜2 監獄島のわらべ唄','acronym' => 'PS2版'),
    array('id' => '103','name' => 'かまいたちの夜2 監獄島のわらべ唄 PlayStation 2 the Best','acronym' => 'PS2 廉価版'),
    array('id' => '102','name' => 'かまいたちの夜2 監獄島のわらべ唄 スペシャルパッケージ','acronym' => 'PS2 SPパッケージ版'),
    array('id' => '353','name' => 'カルタグラ～ツキ狂イノ病～','acronym' => 'PC版'),
    array('id' => '354','name' => 'カルタグラ～ツキ狂イノ病～ 廉価版','acronym' => 'PC 廉価版'),
    array('id' => '712','name' => 'カルタグラ～魂ノ苦悩～','acronym' => 'PS2版'),
    array('id' => '714','name' => 'カルタグラ～魂ノ苦悩～ 2800コレクション','acronym' => 'PS2 廉価版'),
    array('id' => '713','name' => 'カルタグラ～魂ノ苦悩～ 初回限定版','acronym' => 'PS2 初回限定版'),
    array('id' => '407','name' => 'キャサリン','acronym' => 'PS3版'),
    array('id' => '408','name' => 'キャサリン','acronym' => 'XB360版'),
    array('id' => '730','name' => 'キャサリン ベストセレクション','acronym' => 'PS3 廉価版'),
    array('id' => '731','name' => 'キャサリン・フルボディ','acronym' => 'PS4版'),
    array('id' => '732','name' => 'キャサリン・フルボディ','acronym' => 'Vita版'),
    array('id' => '401','name' => 'クリオスタシス　日本語版','acronym' => '通常版'),
    array('id' => '113','name' => 'グレゴリーホラーショー ソウルコレクター','acronym' => '通常版'),
    array('id' => '114','name' => 'クロックタワー','acronym' => 'SFC版'),
    array('id' => '116','name' => 'クロックタワー for ワンダースワン','acronym' => 'ワンダースワン版'),
    array('id' => '874','name' => 'クロックタワー VC版','acronym' => 'Wii VC版'),
    array('id' => '875','name' => 'クロックタワー VC版','acronym' => 'WiiU VC版'),
    array('id' => '115','name' => 'クロックタワー ザ・ファースト・フィアー','acronym' => 'PS版'),
    array('id' => '876','name' => 'クロックタワー ザ・ファースト・フィアー','acronym' => 'ゲームアーカイブス'),
    array('id' => '119','name' => 'クロックタワー・ゴーストヘッド','acronym' => '通常版'),
    array('id' => '878','name' => 'クロックタワー・ゴーストヘッド','acronym' => 'ゲームアーカイブス'),
    array('id' => '117','name' => 'クロックタワー2','acronym' => '通常版'),
    array('id' => '877','name' => 'クロックタワー2','acronym' => 'ゲームアーカイブス'),
    array('id' => '118','name' => 'クロックタワー2 ベスト','acronym' => '廉価版'),
    array('id' => '120','name' => 'クロックタワー3','acronym' => '通常版'),
    array('id' => '503','name' => 'ゲゲゲの鬼太郎','acronym' => '通常版'),
    array('id' => '199','name' => 'ゴーストヴァイブレーション','acronym' => '通常版'),
    array('id' => '164','name' => 'ゴーストトラップ','acronym' => '通常版'),
    array('id' => '159','name' => 'ゴーストハンター','acronym' => '通常版'),
    array('id' => '736','name' => 'コープスパーティー BLOOD DRIVE','acronym' => '通常版'),
    array('id' => '737','name' => 'コープスパーティー BLOOD DRIVE 限定版','acronym' => '限定版'),
    array('id' => '440','name' => 'コープスパーティー Book of Shadows','acronym' => '通常版'),
    array('id' => '441','name' => 'コープスパーティー Book of Shadows 初回限定版','acronym' => '初回限定版'),
    array('id' => '734','name' => 'コープスパーティー ブラッドカバー リピーティッドフィアー','acronym' => '3DS版'),
    array('id' => '439','name' => 'コープスパーティー ブラッドカバー リピーティッドフィアー 初回限定版','acronym' => 'PSP 初回限定版'),
    array('id' => '735','name' => 'コープスパーティー ブラッドカバー リピーティッドフィアー 限定版','acronym' => '3DS 限定版'),
    array('id' => '438','name' => 'コープスパーティー ブラッドカバーリピーティッドフィアー','acronym' => 'PSP版'),
    array('id' => '355','name' => 'ゴア・スクリーミング・ショウ','acronym' => 'PC版'),
    array('id' => '754','name' => 'ゴア・スクリーミング・ショウ DVD-PG版','acronym' => 'DVD-PG版'),
    array('id' => '752','name' => 'ゴア・スクリーミング・ショウ UMD-PG Edition','acronym' => 'UMD-PG版'),
    array('id' => '753','name' => 'ゴア・スクリーミング・ショウ Windows7対応版','acronym' => 'PC Win7対応版'),
    array('id' => '756','name' => 'ゴア・スクリーミング・ショウ Windows8.1動作版','acronym' => 'PC Win8.1動作版'),
    array('id' => '757','name' => 'ゴア・スクリーミング・ショウ Windows8.1動作版 DL版','acronym' => 'PC Win8.1動作 DL版'),
    array('id' => '755','name' => 'ゴア・スクリーミング・ショウ 価格改定版','acronym' => 'PC 廉価版'),
    array('id' => '356','name' => 'ゴア・スクリーミング・ショウ 初回特典版','acronym' => 'PC 初回特典版'),
    array('id' => '634','name' => 'この歌が終わったら - When this song is over -','acronym' => 'DVD-PG版'),
    array('id' => '633','name' => 'この歌が終わったら - When this song is over -','acronym' => 'PC版'),
    array('id' => '635','name' => 'この歌が終わったら - When this song is over -','acronym' => 'Vita版'),
    array('id' => '758','name' => 'この歌が終わったら - When this song is over - DL版','acronym' => 'PC DL版'),
    array('id' => '160','name' => 'コワイシャシン～心霊写真奇譚～','acronym' => '通常版'),
    array('id' => '512','name' => 'サイコブレイク','acronym' => 'XB1版'),
    array('id' => '513','name' => 'サイコブレイク','acronym' => 'XB360版'),
    array('id' => '511','name' => 'サイコブレイク','acronym' => 'PS4版'),
    array('id' => '510','name' => 'サイコブレイク','acronym' => 'PS3版'),
    array('id' => '516','name' => 'サイコブレイク2','acronym' => 'Steam版'),
    array('id' => '515','name' => 'サイコブレイク2','acronym' => 'XB1版'),
    array('id' => '514','name' => 'サイコブレイク2','acronym' => 'PS4版'),
    array('id' => '172','name' => 'サイレントヒル','acronym' => '通常版'),
    array('id' => '174','name' => 'サイレントヒル PS one Books','acronym' => 'PS one Books'),
    array('id' => '185','name' => 'サイレントヒル ゼロ','acronym' => '通常版'),
    array('id' => '825','name' => 'サイレントヒル ゼロ コナミ・ザ・ベスト','acronym' => 'コナミ・ザ・ベスト'),
    array('id' => '175','name' => 'サイレントヒル コナミ・ザ・ベスト','acronym' => 'コナミ・ザ・ベスト'),
    array('id' => '173','name' => 'サイレントヒル2','acronym' => 'PS2版'),
    array('id' => '176','name' => 'サイレントヒル2 最期の詩','acronym' => '最期の詩　XB版'),
    array('id' => '177','name' => 'サイレントヒル2 最期の詩','acronym' => '最期の詩　PS2版'),
    array('id' => '178','name' => 'サイレントヒル2 最期の詩 コナミ・ザ・ベスト','acronym' => '最期の詩 PS2 廉価版'),
    array('id' => '179','name' => 'サイレントヒル2 最期の詩 コナミ殿堂セレクション','acronym' => '最期の詩 PS2 再廉価版'),
    array('id' => '180','name' => 'サイレントヒル3','acronym' => 'PS2版'),
    array('id' => '181','name' => 'サイレントヒル3 コナミ・ザ・ベスト','acronym' => 'PS2 廉価版'),
    array('id' => '182','name' => 'サイレントヒル3 コナミ殿堂セレクション','acronym' => 'PS2 再廉価版'),
    array('id' => '183','name' => 'サイレントヒル4 -THE ROOM-','acronym' => 'PS2版'),
    array('id' => '880','name' => 'サイレントヒル4 -THE ROOM-','acronym' => 'ゲームアーカイブス'),
    array('id' => '184','name' => 'サイレントヒル4 -THE ROOM- コナミ・ザ・ベスト','acronym' => 'PS2 廉価版'),
    array('id' => '826','name' => 'サイレントヒル4 -THE ROOM- コナミ殿堂セレクション','acronym' => 'PS2 再廉価版'),
    array('id' => '419','name' => 'シャドウ オブ ザ ダムド','acronym' => 'PS3版'),
    array('id' => '420','name' => 'シャドウ オブ ザ ダムド','acronym' => 'XB360版'),
    array('id' => '636','name' => 'シンギュラリティ','acronym' => 'PS3版'),
    array('id' => '637','name' => 'シンギュラリティ','acronym' => 'XB360版'),
    array('id' => '638','name' => 'シンクロ','acronym' => '通常版'),
    array('id' => '208','name' => 'スウィートホーム','acronym' => '通常版'),
    array('id' => '394','name' => 'スクウェア ミレニアム コレクション第3弾 パラサイト・イヴ2','acronym' => 'スクウェア ミレニアム コレクション'),
    array('id' => '707','name' => 'ストーカー ～ コール オブ プリピャチ ～','acronym' => 'パッケージ版'),
    array('id' => '708','name' => 'ストーカー ～クリアスカイ～','acronym' => 'パッケージ版'),
    array('id' => '285','name' => 'スパイクライブラリー＃005 トワイライトシンドローム～再会～ ','acronym' => 'スパイクライブラリー'),
    array('id' => '884','name' => 'ゾンビ','acronym' => 'XB1版'),
    array('id' => '820','name' => 'ゾンビ','acronym' => 'PS4版'),
    array('id' => '885','name' => 'ゾンビ','acronym' => 'PC版'),
    array('id' => '469','name' => 'ゾンビU','acronym' => 'WiiU版'),
    array('id' => '218','name' => 'ダークメサイア','acronym' => '通常版'),
    array('id' => '361','name' => 'ダイアの約束 ～逢いたくて～','acronym' => '通常版'),
    array('id' => '767','name' => 'ダイアの約束 ～逢いたくて～ DL版','acronym' => 'DL版'),
    array('id' => '221','name' => 'ダブルキャスト','acronym' => 'PS版'),
    array('id' => '222','name' => 'ダブルキャスト PlayStation the Best','acronym' => 'PS 廉価版'),
    array('id' => '350','name' => 'つくとり','acronym' => '通常版'),
    array('id' => '254','name' => 'デッドスペース エクストラクション','acronym' => '通常版'),
    array('id' => '592','name' => 'デッドハウス 再生','acronym' => 'WiiU版'),
    array('id' => '591','name' => 'デッドハウス 再生','acronym' => 'PS4版'),
    array('id' => '593','name' => 'デッドハウス 再生','acronym' => 'Switch版'),
    array('id' => '240','name' => 'デビルマン','acronym' => '通常版'),
    array('id' => '533','name' => 'ドラキュラ ～復活～','acronym' => '通常版'),
    array('id' => '534','name' => 'ドラキュラ2 ～聖域～','acronym' => '通常版'),
    array('id' => '282','name' => 'トワイライトシンドローム スペシャル','acronym' => 'スペシャル'),
    array('id' => '280','name' => 'トワイライトシンドローム-探索編-','acronym' => '通常版'),
    array('id' => '281','name' => 'トワイライトシンドローム-究明編-','acronym' => '通常版'),
    array('id' => '284','name' => 'トワイライトシンドローム～再会～','acronym' => '通常版'),
    array('id' => '286','name' => 'トワイライトシンドローム～再会～ PS one Books','acronym' => 'PS one Books'),
    array('id' => '287','name' => 'トワイライトシンドローム禁じられた都市伝説','acronym' => '通常版'),
    array('id' => '641','name' => 'トワイライトホテル','acronym' => '通常版'),
    array('id' => '642','name' => 'トワイライトホテル ～夜鳴の詩～','acronym' => '夜鳴の詩'),
    array('id' => '773','name' => 'トワイライトホテル 〜夜鳴の詩〜 Windows7対応版 DL版','acronym' => '夜鳴の詩 Win7対応 DL版'),
    array('id' => '835','name' => 'ナナシ ノ 或プリ','acronym' => 'Android版'),
    array('id' => '228','name' => 'ナナシ ノ ゲエム','acronym' => '通常版'),
    array('id' =>   '5','name' => 'ナナシ ノ ゲエム目','acronym' => '通常版'),
    array('id' => '595','name' => 'ネバーエンディングナイトメア','acronym' => 'PS4版'),
    array('id' => '594','name' => 'ネバーエンディングナイトメア','acronym' => 'PC版'),
    array('id' => '596','name' => 'ネバーエンディングナイトメア','acronym' => 'Vita版'),
    array('id' => '279','name' => 'ノクターン','acronym' => '通常版'),
    array('id' => '898','name' => 'バイオハザード アンブレラ・クロニクルズ','acronym' => 'PS4版'),
    array('id' => '261','name' => 'バイオハザード アンブレラ・クロニクルズ','acronym' => 'Wii版'),
    array('id' => '262','name' => 'バイオハザード アンブレラ・クロニクルズ エキスパートパッケージ','acronym' => 'Wii エキスパート版'),
    array('id' => '433','name' => 'バイオハザード オペレーションラクーンシティ','acronym' => 'XB360版'),
    array('id' => '434','name' => 'バイオハザード オペレーションラクーンシティ','acronym' => 'PS3版'),
    array('id' => '455','name' => 'バイオハザード クロニクルズ HDセレクション','acronym' => 'PS3版'),
    array('id' => '787','name' => 'バイオハザード クロニクルズ HDセレクション PlayStation 3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '310','name' => 'バイオハザード コード:ベロニカ 完全版 バイオハザード4 バリューパック','acronym' => 'PS2 ベロニカ＆4 バリューパック'),
    array('id' =>  '15','name' => 'バイオハザード ダークサイド・クロニクルズ','acronym' => 'Wii版'),
    array('id' => '899','name' => 'バイオハザード ダークサイド・クロニクルズ','acronym' => 'PS4版'),
    array('id' => '785','name' => 'バイオハザード ダークサイド・クロニクルズ コレクターズ・パッケージ','acronym' => 'Wii コレクターズ・パッケージ'),
    array('id' => '535','name' => 'バイオハザード リベレーションズ Best Price!','acronym' => '3DS 廉価版'),
    array('id' => '792','name' => 'バイオハザード リベレーションズ アンベールド エディション','acronym' => 'WiiU版'),
    array('id' => '538','name' => 'バイオハザード リベレーションズ アンベールド エディション','acronym' => 'PS4版'),
    array('id' => '537','name' => 'バイオハザード リベレーションズ アンベールド エディション','acronym' => 'XB360版'),
    array('id' => '536','name' => 'バイオハザード リベレーションズ アンベールド エディション','acronym' => 'PS3版'),
    array('id' => '900','name' => 'バイオハザード リベレーションズ アンベールド エディション','acronym' => 'XB1版'),
    array('id' => '539','name' => 'バイオハザード リベレーションズ アンベールド エディション','acronym' => 'Switch版'),
    array('id' => '791','name' => 'バイオハザード リベレーションズ アンベールド エディション PlayStation 3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '540','name' => 'バイオハザード リベレーションズ コレクション','acronym' => 'Switch リベレーションズ コレクション'),
    array('id' => '541','name' => 'バイオハザード リベレーションズ2','acronym' => 'PS3版'),
    array('id' => '546','name' => 'バイオハザード リベレーションズ2','acronym' => 'XB1版'),
    array('id' => '544','name' => 'バイオハザード リベレーションズ2','acronym' => 'Vita版'),
    array('id' => '543','name' => 'バイオハザード リベレーションズ2','acronym' => 'PS4版'),
    array('id' => '542','name' => 'バイオハザード リベレーションズ2 PlayStation 3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '545','name' => 'バイオハザード リベレーションズ2 PlayStation Vita the Best','acronym' => 'Vita 廉価版'),
    array('id' => '423','name' => 'バイオハザード ダークサイド・クロニクルズ Best Price!','acronym' => 'Wii 廉価版'),
    array('id' => '788','name' => 'バイオハザード5 オルタナティブ エディション バイオハザード リバイバルセレクション HDリマスター版 ツインパック','acronym' => '5AE リバセレ ツインパック'),
    array('id' => '789','name' => 'バイオハザード5 オルタナティブ エディション バイオハザード リバイバルセレクション HDリマスター版 ツインパック','acronym' => '5AE リバセレ ツインパック 廉価版'),
    array('id' => '793','name' => 'バイオハザードクロニクルズ バリューパック','acronym' => 'Wii バリューパック'),
    array('id' => '855','name' => 'ハッピープライスセレクション ルイージマンション2','acronym' => '廉価版'),
    array('id' => '680','name' => 'パラケルススの魔剣','acronym' => 'PC版'),
    array('id' => '913','name' => 'パラケルススの魔剣 DL版(PC-9801)','acronym' => 'PC-9801 DL版'),
    array('id' => '914','name' => 'クロックタワー DL版(SFC)','acronym' => 'プロジェクトEGG'),
    array('id' => '901','name' => 'パラサイト・イヴ','acronym' => 'ゲームアーカイブス'),
    array('id' => '233','name' => 'パラサイト・イヴ','acronym' => '通常版'),
    array('id' => '902','name' => 'パラサイト・イヴ2','acronym' => 'ゲームアーカイブス'),
    array('id' => '393','name' => 'パラサイト・イヴ2','acronym' => '通常版'),
    array('id' => '395','name' => 'パラサイト・イヴ2 PS one Books','acronym' => 'PS one Books'),
    array('id' => '230','name' => 'ハングリィ・ゴースト','acronym' => '通常版'),
    array('id' => '273','name' => 'バンパイアハンターD','acronym' => '通常版'),
    array('id' => '275','name' => 'バンパイアハンターD PS one Books','acronym' => 'PS one Books'),
    array('id' => '598','name' => 'ヒア・ゼイ・ライ –眠りし者たち-','acronym' => '通常版'),
    array('id' => '274','name' => 'ビクターホラーコレクション バンパイアハンターD','acronym' => 'ビクターホラーコレクション'),
    array('id' => '410','name' => 'ひぐらしのなく頃に','acronym' => '通常版'),
    array('id' => '842','name' => 'ひぐらしのなく頃に 奉','acronym' => '通常版'),
    array('id' => '843','name' => 'ひぐらしのなく頃に 奉 完全生産限定版','acronym' => '完全生産限定版'),
    array('id' => '670','name' => 'ひぐらしのなく頃に祭','acronym' => '通常版'),
    array('id' => '851','name' => 'ひぐらしのなく頃に祭 お持ち帰りぃ～セット','acronym' => 'お持ち帰りぃ～セット'),
    array('id' => '671','name' => 'ひぐらしのなく頃に祭 カケラ遊び','acronym' => 'カケラ遊び'),
    array('id' => '850','name' => 'ひぐらしのなく頃に祭 カケラ遊び アペンド版','acronym' => 'カケラ遊び アペンド版'),
    array('id' => '673','name' => 'ひぐらしのなく頃に粋','acronym' => 'Vita版'),
    array('id' => '672','name' => 'ひぐらしのなく頃に粋','acronym' => 'PS3版'),
    array('id' => '678','name' => 'ひぐらしのなく頃に絆 一・二巻パック','acronym' => '一・二巻パック版'),
    array('id' => '674','name' => 'ひぐらしのなく頃に絆 第一巻・祟','acronym' => '第一巻・祟版'),
    array('id' => '676','name' => 'ひぐらしのなく頃に絆 第三巻・螺','acronym' => '第三巻・螺'),
    array('id' => '675','name' => 'ひぐらしのなく頃に絆 第二巻・想','acronym' => '第二巻・想'),
    array('id' => '677','name' => 'ひぐらしのなく頃に絆 第四巻・絆','acronym' => '第四巻・絆'),
    array('id' => '156','name' => 'ファーレンハイト','acronym' => 'PC版'),
    array('id' => '155','name' => 'ファーレンハイト','acronym' => 'PS2版'),
    array('id' => '157','name' => 'ファーレンハイトBest Selection of GAMES','acronym' => 'PC 廉価版'),
    array('id' => '838','name' => 'ファタモルガーナの館','acronym' => '3DS版'),
    array('id' => '836','name' => 'ファタモルガーナの館','acronym' => 'PC版'),
    array('id' => '837','name' => 'ファタモルガーナの館','acronym' => 'iOS版'),
    array('id' => '840','name' => 'ファタモルガーナの館 －Another Episodes－','acronym' => 'PC版'),
    array('id' => '839','name' => 'ファタモルガーナの館 -COLLECTED EDITION-','acronym' => 'Vita版'),
    array('id' => '326','name' => 'ファミコンミニ ファミコン探偵倶楽部 消えた後継者 前後編','acronym' => 'GBA版'),
    array('id' => '327','name' => 'ファミコンミニ ファミコン探偵倶楽部PARTII うしろに立つ少女 前後編','acronym' => 'GBA版'),
    array('id' => '319','name' => 'ファミコン探偵倶楽部 消えた後継者 前編','acronym' => '前編'),
    array('id' => '320','name' => 'ファミコン探偵倶楽部 消えた後継者 後編','acronym' => '後編'),
    array('id' => '325','name' => 'ファミコン探偵倶楽部PartII うしろに立つ少女','acronym' => 'SFC版'),
    array('id' => '321','name' => 'ファミコン探偵倶楽部PartII うしろに立つ少女','acronym' => 'ファミコンディスクシステム版'),
    array('id' => '644','name' => 'ファンタズム','acronym' => 'SS版'),
    array('id' => '643','name' => 'ファンタズム','acronym' => 'PC版'),
    array('id' => '645','name' => 'ファンタズム2 -切り裂かれた記憶- 完全日本語版','acronym' => '通常版'),
    array('id' => '646','name' => 'フェアリーテイル・アンコール','acronym' => '通常版'),
    array('id' => '647','name' => 'フェアリーテイル・シンフォニー','acronym' => 'シンフォニー'),
    array('id' => '809','name' => 'フェアリーテイル・シンフォニー Another Side DL版','acronym' => 'シンフォニー Another Side DL版'),
    array('id' => '648','name' => 'フェアリーテイル・レクイエム','acronym' => '通常版'),
    array('id' => '153','name' => 'プリズナー オブ アイス','acronym' => '通常版'),
    array('id' => '649','name' => 'ブルースティンガー','acronym' => '通常版'),
    array('id' => '357','name' => 'フルメタルBOX','acronym' => 'フルメタルBOX'),
    array('id' => '548','name' => 'フロムダスクティルドーン','acronym' => '通常版'),
    array('id' => '205','name' => 'ベストプライス Juggernaut～戦慄の扉～','acronym' => '廉価版'),
    array('id' => '122','name' => 'ベストプライス黒ノ十三','acronym' => '廉価版'),
    array('id' => '351','name' => 'ほとせなる呪 ちとせなる詛','acronym' => '通常版'),
    array('id' => '550','name' => 'ホラート －ディアトロフ峠の惨劇－','acronym' => 'PS4版'),
    array('id' => '145','name' => 'みてはいけない','acronym' => '通常版'),
    array('id' => '143','name' => 'ムーンライトシンドローム','acronym' => '通常版'),
    array('id' => '144','name' => 'ムーンライトシンドローム PlayStation the Best','acronym' => 'PlayStation the Best'),
    array('id' => '203','name' => 'メトロ THE BEST 実話怪談「新耳袋」一ノ章','acronym' => '廉価版'),
    array('id' => '715','name' => 'やるドラ ポータブル ダブルキャスト','acronym' => 'PSP DL版'),
    array('id' => '223','name' => 'やるドラ ポータブル ダブルキャスト','acronym' => 'PSP版'),
    array('id' => '682','name' => 'ラプラスの魔','acronym' => 'PCエンジン版'),
    array('id' => '681','name' => 'ラプラスの魔','acronym' => 'PC版'),
    array('id' => '683','name' => 'ラプラスの魔','acronym' => 'SFC版'),
    array('id' => '911','name' => 'ラプラスの魔 DL版(PC-8801)','acronym' => 'プロジェクトEGG PC-8801'),
    array('id' => '910','name' => 'ラプラスの魔 DL版(PC-9801)','acronym' => 'プロジェクトEGG PC9801'),
    array('id' => '912','name' => 'ラプラスの魔 DL版(X68000)','acronym' => 'プロジェクトEGG X68000'),
    array('id' => '196','name' => 'リング∞','acronym' => '通常版'),
    array('id' =>  '69','name' => 'ルールオブローズ','acronym' => '通常版'),
    array('id' => '123','name' => 'ルイージマンション','acronym' => '通常版'),
    array('id' => '854','name' => 'ルイージマンション2','acronym' => '通常版'),
    array('id' => '853','name' => 'Left 4 Dead 2 プラチナコレクション','acronym' => 'XB360 廉価版'),
    array('id' =>  '42','name' => 'Left 4 Dead','acronym' => 'XB360版'),
    array('id' =>  '41','name' => 'Left 4 Dead','acronym' => 'PC版'),
    array('id' =>  '44','name' => 'Left 4 Dead プラチナコレクション','acronym' => 'XB360 廉価版'),
    array('id' =>  '45','name' => 'Left 4 Dead 2','acronym' => 'XB360版'),
    array('id' => '651','name' => '一夜怪談','acronym' => 'iOS版'),
    array('id' => '650','name' => '一夜怪談','acronym' => '携帯電話版'),
    array('id' => '652','name' => '一夜怪談','acronym' => 'Android版'),
    array('id' => '653','name' => '九十九の奏〜欠け月の夜想曲〜','acronym' => 'パッケージ版'),
    array('id' => '769','name' => '九十九の奏〜欠け月の夜想曲〜 DL版','acronym' => 'DL版'),
    array('id' => '112','name' => '九怨-kuon-','acronym' => '通常版'),
    array('id' => '372','name' => '二重影','acronym' => 'PC版'),
    array('id' => '711','name' => '二重影','acronym' => 'DC版'),
    array('id' => '250','name' => '人魚の烙印','acronym' => '通常版'),
    array('id' => '654','name' => '公開されなかった手記','acronym' => '通常版'),
    array('id' => '904','name' => '厄-友情談疑-','acronym' => 'ゲームアーカイブス'),
    array('id' => '141','name' => '厄-友情談疑-','acronym' => '通常版'),
    array('id' => '142','name' => '厄痛 ～呪いのゲーム～','acronym' => '通常版'),
    array('id' => '905','name' => '厄痛 ～呪いのゲーム～','acronym' => 'ゲームアーカイブス'),
    array('id' => '655','name' => '古伝降霊術 百物語〜ほんとにあった怖い話〜','acronym' => '通常版'),
    array('id' => '656','name' => '古伝降霊術 百物語〜ほんとにあった怖い話〜 サタコレ','acronym' => '廉価版'),
    array('id' => '242','name' => '吸血姫夕維～千夜抄～','acronym' => 'PC版'),
    array('id' => '241','name' => '吸血姫夕維～千夜抄～','acronym' => 'PS2版'),
    array('id' => '243','name' => '吸血姫夕維～千夜抄～ 初回限定版','acronym' => 'PC 初回限定版'),
    array('id' => '201','name' => '四八（仮）','acronym' => '通常版'),
    array('id' => '128','name' => '夕闇通り探検隊','acronym' => '通常版'),
    array('id' => '138','name' => '夜光虫','acronym' => 'SFC版'),
    array('id' => '139','name' => '夜光虫GB','acronym' => 'GBC版'),
    array('id' => '140','name' => '夜光虫II 殺人経路','acronym' => '通常版'),
    array('id' => '504','name' => '夜廻','acronym' => '通常版'),
    array('id' => '906','name' => '夜想曲','acronym' => 'ゲームアーカイブス'),
    array('id' => '133','name' => '夜想曲','acronym' => '通常版'),
    array('id' => '134','name' => '夜想曲 PlayStation the Best','acronym' => 'PlayStation the Best'),
    array('id' => '135','name' => '夜想曲 PS one Books','acronym' => 'PS one Books'),
    array('id' => '907','name' => '夜想曲2','acronym' => 'ゲームアーカイブス'),
    array('id' => '136','name' => '夜想曲2','acronym' => '通常版'),
    array('id' => '137','name' => '夜想曲2 PS one Books','acronym' => 'PS one Books'),
    array('id' => '219','name' => '大幽霊屋敷～浜村淳の実話怪談～','acronym' => '通常版'),
    array('id' => '220','name' => '大幽霊屋敷～浜村淳の実話怪談～ 廉価版','acronym' => '廉価版'),
    array('id' =>  '94','name' => '学校であった怖い話','acronym' => 'SFC版'),
    array('id' => '236','name' => '学校であった怖い話S','acronym' => '通常版'),
    array('id' => '870','name' => '学校であった怖い話S','acronym' => 'ゲームアーカイブス'),
    array('id' =>  '96','name' => '学校の怪談DS','acronym' => '通常版'),
    array('id' => '202','name' => '実話怪談「新耳袋」一ノ章','acronym' => '通常版'),
    array('id' => '375','name' => '幽明境を異にする','acronym' => 'PC版'),
    array('id' => '814','name' => '幽明境を異にする DVD-PG版','acronym' => 'DVD-PG版'),
    array('id' => '376','name' => '幽明境を異にする 簡易パッケージ版','acronym' => 'PC 簡易パッケージ版'),
    array('id' =>  '90','name' => '弟切草','acronym' => 'SFC版'),
    array('id' =>  '92','name' => '弟切草-蘇生篇- PlayStation the Best','acronym' => 'PlayStation the Best'),
    array('id' => '867','name' => '弟切草-蘇生篇-','acronym' => 'ゲームアーカイブス'),
    array('id' =>  '91','name' => '弟切草-蘇生篇-','acronym' => '通常版'),
    array('id' => '234','name' => '彼岸島','acronym' => '通常版'),
    array('id' => '248','name' => '彼岸花','acronym' => 'GBA版'),
    array('id' => '249','name' => '彼岸花','acronym' => 'PS2版'),
    array('id' => '657','name' => '彼岸花の咲く夜に','acronym' => 'PC版'),
    array('id' => '658','name' => '彼岸花の咲く夜に','acronym' => '3DS版'),
    array('id' => '451','name' => '心霊カメラ ～憑いてる手帳～','acronym' => '通常版'),
    array('id' => '556','name' => '心霊旅館からの脱出','acronym' => 'Android版'),
    array('id' => '919','name' => '心霊旅館からの脱出','acronym' => 'iOS版'),
    array('id' =>  '72','name' => '忌火起草','acronym' => '通常版'),
    array('id' =>  '73','name' => '忌火起草 解明編','acronym' => '通常版'),
    array('id' => '679','name' => '怪奇！ ドリル男の恐怖','acronym' => '通常版'),
    array('id' => '748','name' => '怪奇！ ドリル男の恐怖 DL版','acronym' => 'DL版'),
    array('id' => '111','name' => '恐怖体験 呪怨','acronym' => '通常版'),
    array('id' => '108','name' => '恐怖新聞','acronym' => '通常版'),
    array('id' => '110','name' => '恐怖新聞【平成版】怪奇! 心霊ファイル コナミ ザ ベスト','acronym' => '廉価版'),
    array('id' => '109','name' => '恐怖新聞【平成版】怪奇！心霊ファイル','acronym' => '通常版'),
    array('id' => '659','name' => '悪魔の招待状','acronym' => '通常版'),
    array('id' => '660','name' => '昏き祟りの森で','acronym' => 'PC版'),
    array('id' => '661','name' => '昏き祟りの森で','acronym' => 'DVD-PG版'),
    array('id' => '751','name' => '昏き祟りの森で DL版','acronym' => 'PC DL版'),
    array('id' => '224','name' => '晦-つきこもり-','acronym' => 'SFC版'),
    array('id' => '886','name' => '晦-つきこもり- VC版','acronym' => 'Wii VC版'),
    array('id' => '887','name' => '晦-つきこもり- VC版','acronym' => 'WiiU VC版'),
    array('id' => '269','name' => '最終電車','acronym' => 'PS版'),
    array('id' => '272','name' => '最終電車','acronym' => 'PS2版'),
    array('id' => '271','name' => '最終電車 再廉価版','acronym' => 'PS 再廉価版'),
    array('id' => '270','name' => '最終電車 廉価版','acronym' => 'PS 廉価版'),
    array('id' => '385','name' => '月陽炎 ～つきかげろう～','acronym' => '通常版'),
    array('id' => '386','name' => '月陽炎 ～つきかげろう～ DVD edition','acronym' => 'DVD edition'),
    array('id' => '768','name' => '月陽炎 ～つきかげろう～ DVD edition DL版','acronym' => 'DVD edition DL版'),
    array('id' => '329','name' => '朝の来ない夜に抱かれて -ETERNAL NIGHT-','acronym' => '通常版'),
    array('id' => '330','name' => '朝の来ない夜に抱かれて -ETERNAL NIGHT- 初回版','acronym' => '初回版'),
    array('id' => '331','name' => '朝の来ない夜に抱かれて -ETERNAL NIGHT- F&Cカード付特別版 初回版','acronym' => 'F&Cカード付特別版'),
    array('id' => '721','name' => '朝の来ない夜に抱かれて- ETERNAL NIGHT- DL版','acronym' => 'DL版'),
    array('id' => '359','name' => '果てしなく青い、この空の下で…。','acronym' => '通常版'),
    array('id' => '802','name' => '果てしなく青い、この空の下で…。 DL版','acronym' => 'DL版'),
    array('id' => '360','name' => '果てしなく青い、この空の下で…。 完全版','acronym' => '完全版'),
    array('id' => '803','name' => '果てしなく青い、この空の下で…。 完全版 DL版','acronym' => '完全版 DL版'),
    array('id' => '127','name' => '歪みの国のアリス','acronym' => '携帯電話版'),
    array('id' =>  '93','name' => '歸らずの森','acronym' => '通常版'),
    array('id' => '558','name' => '死印','acronym' => 'Vita版'),
    array('id' => '561','name' => '死印','acronym' => 'Switch版'),
    array('id' => '557','name' => '死印','acronym' => 'Vita版'),
    array('id' => '739','name' => '死印 "開封厳禁！呪われた限定版"','acronym' => 'PS4 限定版'),
    array('id' => '882','name' => '死者の呼ぶ館','acronym' => 'ゲームアーカイブス'),
    array('id' => '200','name' => '死者の呼ぶ館','acronym' => '通常版'),
    array('id' => '362','name' => '沙耶の唄','acronym' => '通常版'),
    array('id' => '363','name' => '沙耶の唄 Nitro The Best! Vol.2','acronym' => '廉価版'),
    array('id' => '760','name' => '沙耶の唄 Nitro The Best! Vol.2 Windows 10対応版','acronym' => 'Win10対応版'),
    array('id' => '761','name' => '沙耶の唄 Nitro The Best! Vol.2 Windows 10対応版 DL版','acronym' => 'Win10対応 DL版'),
    array('id' =>  '60','name' => '流行り神 PORTABLE 警視庁怪異事件ファイル','acronym' => 'PSP版'),
    array('id' =>  '61','name' => '流行り神 PORTABLE 警視庁怪異事件ファイル The Best Price','acronym' => 'PSP 廉価版'),
    array('id' =>  '59','name' => '流行り神 Revenge 警視庁怪異事件ファイル','acronym' => 'PS2 廉価版'),
    array('id' =>  '58','name' => '流行り神 警視庁怪異事件ファイル','acronym' => 'PS2版'),
    array('id' =>  '65','name' => '流行り神2 PORTABLE 警視庁怪異事件ファイル','acronym' => 'PSP版'),
    array('id' =>  '66','name' => '流行り神2 PORTABLE 警視庁怪異事件ファイル The Best Price','acronym' => 'PSP 廉価版'),
    array('id' =>  '63','name' => '流行り神2 警視庁怪異事件ファイル','acronym' => 'PS2版'),
    array('id' =>  '64','name' => '流行り神2 警視庁怪異事件ファイル The Best Price','acronym' => 'PS2 廉価版'),
    array('id' =>  '67','name' => '流行り神2DS 都市伝説怪異事件','acronym' => 'DS版'),
    array('id' =>   '4','name' => '流行り神3 警視庁怪異事件ファイル','acronym' => '通常版'),
    array('id' => '797','name' => '流行り神3 警視庁怪異事件ファイル The Best Price','acronym' => '廉価版'),
    array('id' =>  '62','name' => '流行り神DS 都市伝説怪異事件','acronym' => 'DS版'),
    array('id' => '506','name' => '深夜廻','acronym' => 'PS4版'),
    array('id' => '505','name' => '深夜廻','acronym' => 'Vita版'),
    array('id' => '662','name' => '漆黒のシャルノス -What a beautiful tomorrow-','acronym' => '通常版'),
    array('id' => '663','name' => '漆黒のシャルノス Full voice ReBORN','acronym' => 'ReBORN'),
    array('id' => '763','name' => '漆黒のシャルノス Full voice ReBORN DL版','acronym' => 'ReBORN DL版'),
    array('id' => '383','name' => '瀬里奈','acronym' => '通常版'),
    array('id' => '384','name' => '瀬里奈 KAGUYA コレクション','acronym' => '廉価版'),
    array('id' => '766','name' => '瀬里奈 KAGUYA コレクション DL版','acronym' => 'DL版'),
    array('id' => '374','name' => '牝姫の虜 ～廃校舎の制服少女～','acronym' => 'PC版'),
    array('id' => '812','name' => '牝姫の虜 ～廃校舎の制服少女～ DVD-PG版','acronym' => 'DVD-PG版'),
    array('id' => '724','name' => '狗哭','acronym' => '通常版'),
    array('id' => '722','name' => '狗哭 DL版','acronym' => 'DL版'),
    array('id' => '665','name' => '狗哭 Windows8.1動作版','acronym' => 'Win8.1動作版'),
    array('id' => '725','name' => '狗哭 Windows8.1動作版 DL版','acronym' => 'Win8.1動作 DL版'),
    array('id' => '723','name' => '狗哭 価格改定版','acronym' => '廉価版'),
    array('id' => '562','name' => '男子校であった怖い話','acronym' => 'PC版'),
    array('id' => '666','name' => '疼き～淫欲に満ちる月～','acronym' => '通常版'),
    array('id' => '729','name' => '疼き～淫欲に満ちる月～ DL版','acronym' => 'DL版'),
    array('id' => '601','name' => '真 流行り神','acronym' => 'PS3版'),
    array('id' => '602','name' => '真 流行り神','acronym' => 'Vita版'),
    array('id' => '604','name' => '真 流行り神 The Best Price','acronym' => 'Vita 廉価版'),
    array('id' => '603','name' => '真 流行り神 The Best Price','acronym' => 'PS3 廉価版'),
    array('id' => '613','name' => '真 流行り神 パンデミック編','acronym' => 'パンデミック編 iOS版'),
    array('id' => '607','name' => '真 流行り神 パンデミック編','acronym' => 'パンデミック編 Android版'),
    array('id' => '611','name' => '真 流行り神 ブラインドマン編','acronym' => 'ブラインドマン編 iOS版'),
    array('id' => '605','name' => '真 流行り神 ブラインドマン編','acronym' => 'ブラインドマン編 Android版'),
    array('id' => '609','name' => '真 流行り神 人形編','acronym' => '人形編 Android版'),
    array('id' => '615','name' => '真 流行り神 人形編','acronym' => '人形編 iOS版'),
    array('id' => '614','name' => '真 流行り神 寄生虫編','acronym' => '寄生虫編 iOS版'),
    array('id' => '608','name' => '真 流行り神 寄生虫編','acronym' => '寄生虫編 Android版'),
    array('id' => '606','name' => '真 流行り神 悪霊編','acronym' => '悪霊編 Android版'),
    array('id' => '612','name' => '真 流行り神 悪霊編','acronym' => '悪霊編 iOS版'),
    array('id' => '616','name' => '真 流行り神 秘密クラブ編','acronym' => '秘密クラブ編 iOS版'),
    array('id' => '610','name' => '真 流行り神 秘密クラブ編','acronym' => '秘密クラブ編 Android版'),
    array('id' => '617','name' => '真 流行り神2','acronym' => 'PS4版'),
    array('id' => '618','name' => '真 流行り神2','acronym' => 'PS3版'),
    array('id' => '619','name' => '真 流行り神2','acronym' => 'Vita版'),
    array('id' => '445','name' => '真かまいたちの夜 11人目の訪問者','acronym' => 'Vita版'),
    array('id' => '444','name' => '真かまいたちの夜 11人目の訪問者','acronym' => 'PS3版'),
    array('id' => '741','name' => '真かまいたちの夜 11人目の訪問者 PlayStation 3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '742','name' => '真かまいたちの夜 11人目の訪問者 PlayStation Vita the Best','acronym' => 'Vita 廉価版'),
    array('id' => '728','name' => '祝姫','acronym' => 'PC版'),
    array('id' => '564','name' => '祝姫 -祀-','acronym' => 'PS4版'),
    array('id' => '565','name' => '祝姫 -祀-','acronym' => 'Vita版'),
    array('id' => '563','name' => '祝姫 DL版','acronym' => 'PC DL版'),
    array('id' =>  '70','name' => '稲川淳二 恐怖の屋敷','acronym' => '通常版'),
    array('id' =>  '71','name' => '稲川淳二 恐怖の屋敷 廉価版','acronym' => '廉価版'),
    array('id' => '667','name' => '稲川淳二 真夜中のタクシー','acronym' => '通常版'),
    array('id' => '668','name' => '稲川淳二 真夜中のタクシー 廉価版','acronym' => '廉価版'),
    array('id' => '669','name' => '紅い夜、星の囁きを聴け','acronym' => '通常版'),
    array('id' => '368','name' => '肢体を洗う','acronym' => '通常版'),
    array('id' => '762','name' => '肢体を洗う【Windows10対応】 DL版','acronym' => 'Win10対応 DL版'),
    array('id' => '555','name' => '脱出×和風ホラー：夢怨','acronym' => 'Android版'),
    array('id' => '554','name' => '脱出×和風ホラー：夢怨','acronym' => 'iOS版'),
    array('id' => '328','name' => '腐り姫～euthanasia～','acronym' => '通常版'),
    array('id' => '750','name' => '腐り姫～euthanasia～ DL版','acronym' => 'DL版'),
    array('id' => '749','name' => 'Liar-soft Selection 01 腐り姫～euthanasia～','acronym' => '廉価版'),
    array('id' => '332','name' => '蛍子','acronym' => '通常版'),
    array('id' => '333','name' => '蛍子 初回版','acronym' => '初回版'),
    array('id' => '373','name' => '蜜柑','acronym' => '通常版'),
    array('id' => '811','name' => '蜜柑 DL版','acronym' => 'DL版'),
    array('id' => '377','name' => '螺旋回廊','acronym' => '通常版'),
    array('id' => '819','name' => '螺旋回廊 DL版','acronym' => 'DL版'),
    array('id' => '379','name' => '螺旋回廊 復刻版','acronym' => '復刻版'),
    array('id' => '378','name' => '螺旋回廊 限定版','acronym' => '限定版'),
    array('id' => '380','name' => '螺旋回廊2','acronym' => '通常版'),
    array('id' => '381','name' => '螺旋回廊2 限定版','acronym' => '限定版'),
    array('id' =>  '25','name' => '赤川次郎月の光 ～沈める鐘の殺人～','acronym' => 'DS版'),
    array('id' =>  '23','name' => '赤川次郎月の光 ～沈める鐘の殺人～','acronym' => 'PS2版'),
    array('id' =>  '24','name' => '赤川次郎月の光 Super Best Collection','acronym' => 'PS2 廉価版'),
    array('id' =>  '86','name' => '逢魔が時','acronym' => '通常版'),
    array('id' =>  '87','name' => '逢魔が時 PS one Books','acronym' => '廉価版'),
    array('id' =>  '88','name' => '逢魔が時2','acronym' => '通常版'),
    array('id' =>  '89','name' => '逢魔が時2 PS one Books','acronym' => '廉価版'),
    array('id' => '129','name' => '遊星からの物体X','acronym' => 'PC版'),
    array('id' => '733','name' => '閉ざされた病棟 -DEMENTIUM II-','acronym' => '通常版'),
    array('id' => '151','name' => '閉鎖病院','acronym' => '通常版'),
    array('id' => '152','name' => '閉鎖病院 廉価版','acronym' => '廉価版'),
    array('id' => '467','name' => '闇からのいざない TENEBRAE I','acronym' => '通常版'),
    array('id' => '468','name' => '闇からのいざない TENEBRAE I 限定版','acronym' => '限定版'),
    array('id' => '132','name' => '闇吹く夏 帝都物語ふたたび','acronym' => '通常版'),
    array('id' => '358','name' => '闇色の童話','acronym' => '通常版'),
    array('id' => '365','name' => '雑音領域','acronym' => '通常版'),
    array('id' => '367','name' => '雑音領域 L.A.C.カード版','acronym' => 'L.A.C.カード版'),
    array('id' => '759','name' => '雑音領域 Windows7対応版 DL版','acronym' => 'PC Windows7対応 DL版'),
    array('id' => '566','name' => '零～濡鴉ノ巫女～','acronym' => 'パッケージ版'),
    array('id' => '567','name' => '零～濡鴉ノ巫女～ DL版','acronym' => 'DL版'),
    array('id' =>  '32','name' => '零～zero～','acronym' => 'PS2版'),
    array('id' =>  '33','name' => '零～zero～ PlayStation2 the Best','acronym' => 'PS2 廉価版'),
    array('id' =>  '38','name' => '零～刺青ノ聲～','acronym' => 'PS2版'),
    array('id' =>  '39','name' => '零～刺青の聲～ PlayStation2 the Best','acronym' => 'PS2 廉価版'),
    array('id' =>  '40','name' => '零～月蝕の仮面～','acronym' => '通常版'),
    array('id' => '452','name' => '零～眞紅の蝶～','acronym' => 'Wii版'),
    array('id' => '883','name' => '零～真紅の蝶～ DL版','acronym' => 'WiiU DL版'),
    array('id' =>  '35','name' => '零～紅い蝶～','acronym' => 'PS2版'),
    array('id' =>  '36','name' => '零～紅い蝶～ PlayStation2 the Best','acronym' => 'PS2 廉価版'),
    array('id' => '621','name' => '霊刻 -池田貴族心霊研究所-','acronym' => '通常版'),
    array('id' => '622','name' => '霊刻 -池田貴族心霊研究所- PS one Books','acronym' => '廉価版'),
    array('id' => '147','name' => '魔女たちの眠り','acronym' => 'SFC版'),
    array('id' => '148','name' => '魔女たちの眠り 完全版','acronym' => 'PC版'),
    array('id' => '149','name' => '魔女たちの眠り-復活祭-','acronym' => '通常版'),
    array('id' => '903','name' => '魔女たちの眠り-復活祭-','acronym' => 'ゲームアーカイブス'),
    array('id' => '150','name' => '魔女たちの眠り-復活祭- PS one Books','acronym' => 'PS one Books'),
    array('id' => '684','name' => '黒き死の仮面','acronym' => '通常版'),
    array('id' => '121','name' => '黒ノ十三','acronym' => '通常版'),
    array('id' => '337','name' => '黒の断章 THE Literary Fragment DOS/V版','acronym' => 'DOS/V版'),
    array('id' => '336','name' => '黒の断章 THE Literary Fragment PC-9801版','acronym' => 'PC-9801版'),
    array('id' => '158','name' => '黒の断章 The Literary Fragment SS版','acronym' => 'SS版'),
    array('id' => '335','name' => '黒の断章 The Literary Fragment DVD版','acronym' => 'PC DVD版'),
    array('id' => '334','name' => '黒の断章 The Literary Fragment for Windows SS改定版','acronym' => 'Windows SS改定版'),
    array('id' => '786','name' => 'バイオハザード アンブレラ・クロニクルズ Best Price!','acronym' => 'Wii 廉価版'),
    array('id' => '263','name' => 'バイオハザード アンブレラ・クロニクルズ Best Price!','acronym' => 'Wii 再廉価版'),
    array('id' => '473','name' => 'biohazard HD REMASTER PlayStation 3 the Best','acronym' => 'PS3 廉価版'),
    array('id' => '472','name' => 'biohazard HD REMASTER コレクターズ・パッケージ','acronym' => 'PS3版 コレクターズ・バッケージ'),
    array('id' => '301','name' => 'BIOHAZARD Deadly Silence BestPrice!','acronym' => '廉価版'),
    array('id' => '300','name' => 'BIOHAZARD Deadly Silence Limited Pack','acronym' => 'Limited Pack'),
    array('id' => '302','name' => 'BIOHAZARD Deadly Silence NEW BestPrice! 2000','acronym' => '再廉価版'),
    array('id' => '130','name' => '遊星からの物体X episodeII','acronym' => 'PS2版'),
    array('id' => '131','name' => '遊星からの物体X episodeII コナミ・ザ・ベスト','acronym' => 'PS2 廉価版'),
    array('id' => '461','name' => 'Dの食卓','acronym' => 'SS版'),
    array('id' => '462','name' => 'サタコレ Dの食卓','acronym' => 'SS 廉価版'),
    array('id' => '782','name' => 'BIOHAZARD REVIVAL SELECTION PlayStation 3 the Best','acronym' => 'リバセレ PS3 廉価版'),
    array('id' => '783','name' => 'BIOHAZARD REVIVAL SELECTION PlayStation 3 the Best','acronym' => 'リバセレ PS3 再廉価版'),
    array('id' => '795','name' => 'biohazard4 Wii Edition Best Price!','acronym' => 'Wii 再廉価版'),
    array('id' => '317','name' => 'biohazard4 Wii Edition Best Price!','acronym' => 'Wii 廉価版'),
    array('id' => '780','name' => 'biohazard0 Best Price!','acronym' => 'Wii 廉価版'),
    array('id' => '475','name' => 'biohazard0 Best Price!','acronym' => 'Wii 再廉価版'),
    array('id' => '479','name' => 'biohazard4','acronym' => 'PS4版'),
    array('id' => '480','name' => 'biohazard4','acronym' => 'PS4 DL版'),
    array('id' => '486','name' => 'BIOHAZARD6','acronym' => 'PS4 DL版'),
    array('id' => '485','name' => 'BIOHAZARD6','acronym' => 'PS4版'),
    array('id' => '687','name' => 'Dead By Daylight 北米版','acronym' => 'PS4版'),
    array('id' => '889','name' => 'Dead by Daylight: スペシャルエディション','acronym' => 'PS4 DL版'),
    array('id' => '483','name' => 'BIOHAZARD5','acronym' => 'PS4 DL版'),
    array('id' => '482','name' => 'BIOHAZARD5','acronym' => 'PS4版'),
    array('id' => '743','name' => 'EXTRAVAGANZA～蟲愛でる少女～ Windows8.1動作版','acronym' => 'PC Win8.1動作版'),
    array('id' => '744','name' => 'EXTRAVAGANZA～蟲愛でる少女～ 価格改定版','acronym' => 'PC 価格改定版'),
    array('id' => '154','name' => 'F.E.A.R.','acronym' => 'PC パッケージ版'),
    array('id' => '705','name' => 'F.E.A.R.','acronym' => 'Steam版'),
    array('id' => '560','name' => '死印','acronym' => 'PS4 DL版'),
    array('id' => '559','name' => '死印','acronym' => 'PS4版'),
    array('id' =>   '6','name' => 'F.E.A.R.2 -Project Origin-','acronym' => 'PC パッケージ版'),
    array('id' => '706','name' => 'F.E.A.R.2 -Project Origin-','acronym' => 'Steam版'),
    array('id' => '627','name' => 'Killing Floor','acronym' => 'パッケージ版'),
    array('id' => '626','name' => 'Killing Floor','acronym' => 'Steam版'),
    array('id' => '865','name' => '弟切草 VC版','acronym' => 'Wii VC版'),
    array('id' => '866','name' => '弟切草 VC版','acronym' => 'WiiU VC版'),
    array('id' => '816','name' => '15周年記念・感謝パック ミユウ大全集 DL版','acronym' => 'ミユウ大全集 DL版'),
    array('id' => '815','name' => '幽明境を異にする DL版','acronym' => 'PC DL版'),
    array('id' => '869','name' => '学校であった怖い話 VC版','acronym' => 'WiiU VC版'),
    array('id' => '868','name' => '学校であった怖い話 VC版','acronym' => 'Wii VC版'),
    array('id' => '697','name' => 'Left 4 Dead 2','acronym' => 'PC パッケージ版'),
    array('id' => '698','name' => 'Left 4 Dead 2','acronym' => 'Steam版'),
);
